microsoft/mssql-jdbc

.gitignore
Make the project more friendly for intellij idea users :)
=> gitignore update for intellij idea

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/bvt/bvtTest.java
Added a queryTimeout connection parameter. This parameter will allow setting a default query timeout to every created java.sql.Statement
=> Dev - Added a queryTimeout connection parameter

build.xml
Upgrade azure-keyvault to 0.9.7 according to PR #50
=> Upgrade azure-keyvault to 0.9.7 for ant

pom.xml
this is in relation to issue #59
=> Set the jre8 version as default

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
=> fix the case when columnEncryptionSetting is enabled on Azure hosted VM and connects to Azure SQL database

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/PLPInputStream.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLCollation.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBlob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSQLXML.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java, src/main/java/com/microsoft/sqlserver/jdbc/ScrollWindow.java, src/main/java/com/microsoft/sqlserver/jdbc/SimpleInputStream.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java
Private methods can't be overridden, so declaring them final doesn't make sense
=> Remove final from private methods

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
=> fix issue TVP Handling is causing exception when calling SP with return value #80

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java
=> when socket timeout occured, do not try the second round

src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyColumnMappingTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestSetUp.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestUtil.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestWrapper.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTimeoutTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/SqlTypeMapping.java, src/test/java/com/microsoft/sqlserver/jdbc/bvt/bvtTestSetup.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/ConnectionDriverTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/DBMetadataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/NativeMSSQLDataSourceTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/PoolingTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/TimeoutTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/WarningTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fips/FipsEnvTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java
=> Code formatting

src/main/java/com/microsoft/sqlserver/jdbc/PLPInputStream.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSQLXML.java
Related to this [issue](https://connect.microsoft.com/SQLServer/Feedback/Details/3119620).
=> getBinaryStream defect

src/main/java/com/microsoft/sqlserver/jdbc/DataTypes.java
Replace if with switch for readability and performance reasons.
=> Replace if with switch

.travis.yml, codecov.yml, pom.xml
Pull Request for adding Code Coverage for Open Source Test Cases.
=> Codecoverage

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/StringUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/fips/FipsTest.java
Added setter & getter methods for fips in SQLServerDataSource. Also updated fips related test cases for SQLServerDataSource.
=> Add setFips in SQLServerDataSource.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PQImpsTest.java
=> filter out comments in the beginning of the query

pom.xml
Trying to accomodate practice of development iteration.
=> Adding snapshot to identify nightly / dev builds

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBlob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerNClob.java
=> Lobs materialisation issue 

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBlob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java
=> clarifying public deprecated constructors in Lobs

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPIssuesTest.java
=> fix TVP issue with resultset for varchar(max)

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyISQLServerBulkRecordTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestUtil.java, src/test/java/com/microsoft/sqlserver/testframework/DBResultSet.java, src/test/java/com/microsoft/sqlserver/testframework/DBTable.java, src/test/java/com/microsoft/sqlserver/testframework/Utils.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlDateTime2.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlFloat.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlReal.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlSmallDateTime.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlTime.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlType.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/VariableLengthType.java
Fix to handle precision and scale for TVP and BulkCopy. Fixes #230
=> Big decimal scale precision

.travis.yml, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/TestSavepoint.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
TestCase for SavePoint & enabling configurable logging in testframework.
=> Configurable Logging for TestFramework & savepoint testcases

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
Wrapping error message `java.lang.IllegalArgumentException: contains illegal character for hexBinary` around a SQLServerException.
It is actually a try-catch block, the formatting after adding try-catch causes lots of diffs.
=> Throw SQLServerException when column value for TVP is invalid.

src/main/java/com/microsoft/sqlserver/jdbc/AE.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerEncryptionType.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSortOrder.java
Usage of the Java Enum feature can be improved by the driver. This
commit includes the following changes:
- use ordinal where possible
- make enum fields final where possible
=> Improve enum usage

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/RegressionTest.java
=> fixes metadata caching regression with DDL queries using pstmt

pom.xml
=> update adal4j dependency to version 1.2.0

README.md, pom.xml
adding snapshot to pom file and updating the release versions in readme.
=> Update pom file

src/main/java/com/microsoft/sqlserver/jdbc/Column.java, src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
=> Make send string parameter as unicode impact set/update null

build.gradle
update to com.microsoft.azure:azure-keyvault:**1.0.0**
=> updates gradle dependencies

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java
Reverting Pr #552 due to test failures.
=> Reverting PR 552

src/main/java/com/microsoft/sqlserver/jdbc/Util.java
=> logger security fix

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
This reverts commit f1674afaed273fa84bb86bad00a887e971222d4f.
=> Change 'sendTimeAsDateTime property' back to true - Java7 RTW branch

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
Same changes as #629 for RTW jre7 branch.
=> Added needsPrepare check and removed 99586 error code check (JRE 7 Branch)

pom.xml
Let's update dependent library versions for JUnit Test source code.
=> Update Maven dependency versions for Junit Tests

CHANGELOG.md
=> Added missing changes to 7.1.1 Preview Release changelog 

CHANGELOG.md
=> Remove "country" from changelog

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE/bug_fix.md, .github/PULL_REQUEST_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE/improvements.md, .github/PULL_REQUEST_TEMPLATE/other.md, .github/PULL_REQUEST_TEMPLATE/release.md
Guide Articles : 
- [Creating Issue Templates](https://help.github.com/articles/creating-issue-templates-for-your-repository/)
- [Creating PR Templates](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)
=> Update Issue and Pull Request templates.

src/test/java/com/microsoft/sqlserver/jdbc/fips/FipsTest.java
Self-explanatory as to why this should be removed.
=> Remove comment

src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DateAndTimeTypeTest.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithNullTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/UTF8SupportTest.java
Fixes issues with parallel executions.
=> Fix | Generate primary key constraints randomly

.checkstyle, mssql-jdbc-checkstyle.xml
Adding checkstyle XML to project, to be used in IDE for development/reviews of new changes.
=> Config | Add Checkstyle configuration file

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/DBMetadataTest.java
Fixes thread ID issue in CI's.
=> Test | Close leaking callablestatement

src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java, src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerBulkRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/NTLMAuthentication.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkBatchInsertRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCommon.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerFMTQuery.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParser.java
Fixes issues identified by static analysis tools
=> Fix | SonarQube issues

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java
Compensating for a change meant to be pushed into a later PR but was reverted with the hotfix.
=> Add | Default to null if val is null

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
=> Fix | Changed SQLServerConnection.state to volatile

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
=> Fix | Fixed the issue with getColumns() only returning the first column against Azure DW

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
=> Fix | Fixed getImportedKeys API against Azure Data Warehouse

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
=> Performance | Remove trailing spaces from PreparedStatements queries

src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DataTypesTest.java
=> Remove primary key from test

src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DataTypesTest.java
Don't test this case against 2k08 as it seems to return the string in a different format.
=> Test | LocalDateTime test modifications

src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/test/java/com/microsoft/sqlserver/jdbc/UtilTest.java
=> Fix bracket escaping in Util.parseUrl()

azure-pipelines.yml
Fix adding a new excluded groups to Ex_Groups for CI.
=> CI pipeline fix

src/main/java/com/microsoft/sqlserver/jdbc/Util.java
Fixes issue https://github.com/microsoft/mssql-jdbc/issues/1304.
=> Fix | Use a StringBuilder for 'result'

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/lobs/LobsTest.java
Tests throw a different error because the column name is invalid and cannot be passed into spde.
=> Fix issue when tests throw a different error message when AE is on

src/main/java/com/microsoft/sqlserver/jdbc/KeyStoreProviderCommon.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCertificateUtils.java
=> Check certificate expiry explicitly

build.gradle, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamColumns.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/main/java/com/microsoft/sqlserver/jdbc/dataclassification/SensitivityProperty.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/XADataSourceTest.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/DataClassificationTest.java
=> mssql-jdbc//GreggJuanEduardoPH:dev

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkBatchInsertRecord.java
=> Remove public class and constructor in SQLServerBulkBatchInsertRecord

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> Fix | Removed debug line from IOBuffer

README.md, codecov.yml
We haven't been uploading code coverage for a while now.
=> Remove CodeCov badge

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerError.java
errors from [Troubleshoot transient connection errors in SQL Database and SQL Managed Instance
](https://docs.microsoft.com/en-us/azure/azure-sql/database/troubleshoot-common-connectivity-issues#entlib60-istransient-method-source-code)
=> Add more transient errors for connection retry

src/main/java/com/microsoft/sqlserver/jdbc/tdsparser.java
=> Proposed fix fo #1661

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
Addresses some concerns with ICR pull request.
=> Add new exception error message for Idle Connection Resiliency

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ErrorMessageTest.java
Use 10 * loginTimeout timeout value which is consistent with SqlClient behaviour
=> Fixed ActiveDirectoryInteractive authentication timeout issue

src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/TimeoutTest.java
slow Azure servers could result in timeout errors
=> Add timeout error for tests

src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyISQLServerBulkRecordTest.java
Adding a data record to this bulk copy test to ensure we don't encounter another regression for the scenario.
=> Adding a bulk copy data record to test

CHANGELOG.md, README.md, azure-pipelines.yml, build.gradle, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/tdsparser.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyISQLServerBulkRecordTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ISQLServerBulkRecordIssuesTest.java
=> Fixes for 9.4.1 Hotfix

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
Hi, not sure if tests are passing or not because I haven't managed to run them locally.
Please let me know if you need me to do any changes for this to be merged.
=> SQLServerBulkCopy: Added target field name to conversion error message

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/test/java/com/microsoft/sqlserver/jdbc/ssl/trustmanager/CustomTrustManagerTest.java
Change certificate validation behavior to validate when encryption is negotiated from either the client or the server side, not just the client side.
=> Change certificate validation behavior

src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ISQLServerBulkRecordIssuesTest.java
=> Added exclude tag for Azure DW incompatible tests

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Fixes issue introduced in PR #1669
=> Removed extra call to executeCommand() within connectionCommand()

README.md, build.gradle, mssql-jdbc_auth_LICENSE, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/samples/adaptive/pom.xml, src/samples/alwaysencrypted/pom.xml, src/samples/azureactivedirectoryauthentication/pom.xml, src/samples/connections/pom.xml, src/samples/constrained/pom.xml, src/samples/dataclassification/pom.xml, src/samples/datatypes/pom.xml, src/samples/resultsets/pom.xml, src/samples/sparse/pom.xml
major version bump due to breaking change in PR #1757
=> Update version to 11.1.0

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java
=> Fixes Managed Identity retry interval to exponential backoff properly

src/test/java/com/microsoft/sqlserver/jdbc/MaxResultBufferTest.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
also fixed MaxResultsBuffer test table name conflicts
=> Updated for java 8 compatibility

mssql-jdbc_formatter.xml
Updating maximum length of comment strings in formatter
=> Updating maximum length of comment strings in formatter

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
=> bulk mode insert with NULL GUID value (#1777)

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> Send ALPN as single element

.github/workflows/codeql-analysis.yml, build.gradle, pom.xml
=> JDK 18 Support

src/test/java/com/microsoft/sqlserver/jdbc/SSLCertificateValidation.java, src/test/java/com/microsoft/sqlserver/jdbc/SSLCertificateValidationTest.java
Fixed the reflection used in the ssl cert validation test. This should fix the gradle pipeline.
=> Updated ssl cert validation test

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerAASEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionKeyStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerNoneEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerVSMEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXADataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/dns/DNSUtilities.java, src/main/java/com/microsoft/sqlserver/jdbc/osgi/Activator.java, src/main/java/com/microsoft/sqlserver/jdbc/osgi/SQLServerDataSourceFactory.java
=> Fix build warnings

src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java
=> Fixed typo in API names to align with jaasConfigurationName property

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyResultSetCursorTest.java
=> Fixed length error for not null datetime2 columns

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
Fix for https://github.com/microsoft/mssql-jdbc/issues/1852
=> Fixed race condition with addressList

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
fixes #1849 - depending on timing the attention ack may be processed
=> Removed assert on attention pending check

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/IdleConnectionResiliency.java, src/main/java/com/microsoft/sqlserver/jdbc/NTLMAuthentication.java, src/main/java/com/microsoft/sqlserver/jdbc/PersistentTokenCacheAccessAspect.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerError.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerFMTQuery.java
Hi
I have removed a call to a toString method on String var
ciao
matteo
=> Removed use of toString on a String, empty statements and double parentheses

src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
Reverts microsoft/mssql-jdbc#1912 which needs to be re-worked
=> Revert "BigDecimal Precision/Scale Fix"

pom.xml
latest msal4j hotfix fixed issue with jackson-databind
=> Updated dependency versions

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/IdleConnectionResiliency.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPooledConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SimpleInputStream.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
=> Fixed warnings detected by Sonartype

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerJdbc43.java
=> Fix for setting KeepAlive extended options

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/BasicConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResultSetsWithResiliencyTest.java
=> Clear prepared statement cache on idle connection resiliency reconnections

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> Backporting fix for connecting to the wrong SQLServer host (#1965)

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> Fix connecting to the wrong SQLServer host (#1965)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java
=> Fixed null sql state and error code 0

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
=> Fixed incorrect updateCount (#2013)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java
=> more code cleanup

src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
Fixed 
- https://github.com/microsoft/mssql-jdbc/pull/1912
- https://github.com/microsoft/mssql-jdbc/issues/1489
- https://github.com/microsoft/mssql-jdbc/issues/942
=> Big decimal precision

pom.xml
Fix for https://github.com/microsoft/mssql-jdbc/issues/2068
=> Made jdk.net optional osgi import

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java
Fix for https://github.com/microsoft/mssql-jdbc/issues/2063
=> Accounted for 0 cstmt meta query results

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
Update for https://github.com/microsoft/mssql-jdbc/issues/2071
=> Updated supportsTransactions method

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java
Fix for https://github.com/microsoft/mssql-jdbc/issues/1432
=> XA error correction

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java
Fix for https://github.com/microsoft/mssql-jdbc/issues/2067
=> Passing table name to sp_cursor call

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
=> added SQL query to toString() in SQLServerPreparedStatement

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java
https://github.com/microsoft/mssql-jdbc/issues/2103
=> Fixed token expiration regression with Azure webapps

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
https://github.com/microsoft/mssql-jdbc/issues/2110
=> Fix for applying lockTimeout when redirect mode is set on azure DB

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
Addresses the comment raised on issue 166 here: https://github.com/microsoft/mssql-jdbc/issues/166#issuecomment-1533991652
=> Added missing property value for disableStatmentPooling

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
Error string was missing quote (discovered in LCL files).
=> Fixed error string

src/main/java/com/microsoft/sqlserver/jdbc/Util.java
=> Backport #2209: Reverted the IBM check to vendor check AND added an additional vm name check to remove false positives

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java
revert previously merged #2212 as that caused timing issues
=> Revert retry fix from PR2212

README.md
People should always use the latest bug fix for stability and security reasons.
=> Update README.md: 12.4.1 instead of 12.4.0

pom.xml
Updated azure-security-keyvault-keys dependency to comply with component governance.
=> Updated azure-security-keyvault-keys dependency

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/microsoft/sql/DateTimeOffset.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java
Fixes the `@apiDoc` java doc error.
=> Java doc error fix and formatting

src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java
fixes issue introduced in PR #2382
=> Fix for gradle test failure

pom.xml
Backport of https://github.com/microsoft/mssql-jdbc/pull/2182
=> [Backport] Bouncy castle update

pom.xml
Backport of https://github.com/microsoft/mssql-jdbc/pull/2162
=> [Backport] Updated h2 version

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamRetValue.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
Backport https://github.com/microsoft/mssql-jdbc/pull/2410.
=> [Backport] Execute stored procedures directly for RPC calls (2410)

CHANGELOG.md, README.md, build.gradle, mssql-jdbc_auth_LICENSE, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/samples/adaptive/pom.xml, src/samples/alwaysencrypted/pom.xml, src/samples/azureactivedirectoryauthentication/pom.xml, src/samples/connections/pom.xml, src/samples/constrained/pom.xml, src/samples/dataclassification/pom.xml, src/samples/datatypes/pom.xml, src/samples/resultsets/pom.xml, src/samples/sparse/pom.xml
12.6.2 changelog and version bump.
=> 12.6.2 version bump

pom.xml
Updated bouncy-castle, msal and azure-identity versions.
=> Bumped versions of dependencies

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerMSAL4JUtils.java
Backport of https://github.com/microsoft/mssql-jdbc/pull/2489.
=> [Backport] Change MSAL logging info to FINER (#2489)

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
https://github.com/microsoft/mssql-jdbc/pull/2497
=> [Backport] Timestamp timezone format fix

pom.xml
Github Issue: https://github.com/microsoft/mssql-jdbc/issues/2608
=> Add com.ibm.security.auth.module and com.sun.security.auth.module as option import

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/resources/BulkCopyCSVTestInputComputeColumn.csv
Github Issue -> https://github.com/microsoft/mssql-jdbc/issues/2606
=> Resolve NPE when bulk copy operation is performed on computed column

build.gradle, pom.xml
Integrated Mockito dependency into the JDBC driver codebase.
=> Integrated Mockito dependency into the JDBC driver codebase.

src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java
Reverted Mockito test cases due to AccessToken type conversion issue.
=> Reverted Mockito test cases due to AccessToken type conversion issue.

CHANGELOG.md, README.md, build.gradle, mssql-jdbc_auth_LICENSE, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/samples/adaptive/pom.xml, src/samples/alwaysencrypted/pom.xml, src/samples/azureactivedirectoryauthentication/pom.xml, src/samples/connections/pom.xml, src/samples/constrained/pom.xml, src/samples/dataclassification/pom.xml, src/samples/datatypes/pom.xml, src/samples/resultsets/pom.xml, src/samples/sparse/pom.xml
Description:
Updates for hotfix release 12.10.1 release in various files including: changelog, readme, pom.xml, build.gradle
=> Updates for 12.10.1

src/main/java/microsoft/sql/Vector.java
Vector Support PR : https://github.com/microsoft/mssql-jdbc/pull/2634
=> Added comments for public functions for vector support

pom.xml, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/BulkCopySendTemporalDataTypesAsStringAETest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/EnclaveTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/JDBCEncryptionDecryptionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/MSITest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/MultiUserAKVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/ParameterMetaDataCacheTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/PrecisionScaleTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/RegressionAlwaysEncryptedTest.java, src/test/java/com/microsoft/sqlserver/jdbc/EnclavePackageTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ConcurrentLoginTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ConnectionEncryptionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ConnectionSuspensionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ErrorMessageTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthWithAE.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/PooledConnectionTest.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java, src/test/java/com/microsoft/sqlserver/testframework/Constants.java
Added "requireSecret" exclude tag for tests which require adding a secret to app registration  (#2786)
=> Added "requireSecret" exclude tag for tests which require adding a secret to app registration 
