microsoft/mssql-jdbc

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
Implement getParentLogger
The driver and data source use JUL for logging but do not implement
#getParentLogger.
This commit contains the following changes:
* implement Driver#getParentLogger
* implement DataSource#getParentLogger
* use "com.microsoft.sqlserver.jdbc" as the parent logger
* instead of spaces and tabs on the same line for indentation use
spaces only
* remove the comments
"The driver currently does not implement JDDBC 4.1 APIs".
While technically true these specific methods are implemented now.
* follow driver naming conventions rather than Java naming conventions
* follow driver conventions modifier location rather than Java
conventions
* no tests added since I couldn't find any existing tests for the
driver oder data source class
=> Implement Driver#getParentLogger

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerAeadAes256CbcHmac256EncryptionKey.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerAeadAes256CbcHmac256Factory.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionAzureKeyVaultProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionJavaKeyStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSymmetricKeyCache.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java
Since Java 1.7 there is the StandardCharsets class which provides
constants for frequently used Charsets. Using this also allows us to
remove several UnsupportedEncodingException catch blocks.
* use StandardCharsets in String constructors where possible
* use StandardCharsets in #getBytes where possible
* use StandardCharsets instead of Charset.foreName where possible
=> Use StandardCharsets where possible

src/main/java/com/microsoft/sqlserver/jdbc/StreamError.java
The StreamError class comment says it's serializable because it is held
by SQLServerException. Both statements are wrong.
=> Fix StreamError class comment

Coding_Guidelines.md, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/main/java/com/microsoft/sqlserver/jdbc/TVP.java
This is in relation to issue: https://connect.microsoft.com/SQLServer/Feedback/Details/3100563
It would greatly simplify Tvp usage in the Spring environment.
Per you request the pull request is made from the dev branch.
=> Make Ms Jdbc driver more spring friendly - dev

README.md
@v-mabarw & @v-xiangs  : Can you review Dependency Section in README?
=> Update Dependency section in README

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSetMetaData.java
The driver currently implements some #unwrap methods but for MetaData
* implement DatabaseMetaData#unwrap
* implement ParameterMetaData#unwrap
* implement ResultSetMetaData#unwrap
* use for spaces for indentation where spaces are used
* use tabs for indentation where tabs are used
=> Implement missing MetaData #unwrap methods

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/ReaderInputStream.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLCollation.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSQLXML.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java
The driver spends a lot of time converting from Charset to String and
from String to Charset. Every time checked exceptions have to be
caught. In addition the Charset lookup code is quite involved. It would
be simpler to use Charset everywhere.
=> Use Charset throughout

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
special thanks to @gstojsic , thank you for providing the idea for us.
=> make setObject() handle TVP with schema rather than [odb], when TVP is used with stored procedure

pom.xml
Just a minor version bump fro `0.9.3` to `0.9.7`. The changelog can be found [here](https://github.com/Azure/azure-sdk-for-java/blob/0.9/ChangeLog.txt).
As far as I can tell the only changes are introducing caching, and a bugfix to do with JSON deserialization.
=> Upgrade azure-keyvault to 0.9.7

.gitignore, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java
When using client side cursors, if end of TDS packet is reached, check the status flag for error and handle it.
=> Read SQL Server error message if status flag has DONE_ERROR set.

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionCertificateStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionJavaKeyStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPooledConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet42.java, src/main/java/com/microsoft/sqlserver/jdbc/TVP.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java
Getting rid of redundant type casts makes the code a lot easier to read, and there is no downside to removing them.
=> Remove redundant type casts

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
=> socket timeout implementation for both connection string and data source

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java
Updating SQLServerBulkCopy constructor to throw SQLServerException, and to use default SQLServerBulkCopyOptions if null is passed in option
=> Updates to BulkCopy

src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestSetUp.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestUtil.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestWrapper.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTimeoutTest.java
Test for bulk options and timeout.
=> BulkCopy additional test cases

build.gradle, build.xml, pom.xml
Ant script now runs only bvt test.
=> updates to version number and junit dependencies

src/test/java/com/microsoft/sqlserver/testframework/DBColumn.java, src/test/java/com/microsoft/sqlserver/testframework/DBSchema.java, src/test/java/com/microsoft/sqlserver/testframework/DBTable.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlBinary.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlChar.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlNChar.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlTypeValue.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlVarBinary.java
Support for binary and varbinary type. 
The new files have same header as the rest of test framework, we can apply the changes throughout the source once header format is finalized.
=> Binary and Varbinary types for framework

src/test/java/com/microsoft/sqlserver/testframework/DBResultSet.java
Meanwhile investigating, skipping the verification for now.
=> skip DBResultSet verification.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSetMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/parametermetadata/ParameterMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java
The driver currently implements all #unwrap methods but some of the
matching #isWrapperFor methods are missing. This is caused by the fix
for #12 which should also have included the #isWrapperFor methods.
- implement DatabaseMetaData#isWrapperFor
- implement ParameterMetaData#isWrapperFor
- implement ResultSetMetaData#isWrapperFor
=> Implement missing MetaData #isWrapperFor methods

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/fips/FipsTest.java
Add bunch of negtive test cases & reduced property parameters in case installed certificate for FIPS enabled JVM
=> Add fips connection property

src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java
Access test resource path as URI to avoid white space read as %20 in URL
=> Access test resource path as URI

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
instead of the public API setTVPName
=> Tvp name with stored procedure

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java
For bulkcopy without AE, driver uses source data type to send data. Applying the same rule if destination column is not encrypted.
Only instance where destination data type is used in bulkcopy is when destination is encrypted (due to normalization).
=> Bulk copy with AE

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> Convert socket adaptor to socket

src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyColumnMappingTest.java, src/test/java/com/microsoft/sqlserver/testframework/DBSchema.java, src/test/java/com/microsoft/sqlserver/testframework/DBTable.java
Before, when two random tables are created, there was a small chance that they would have identical schemas. This caused the ImplicitMismatchCM test case to pass when it was expected to fail. Modified creation of destination table to always have a different schema from the source table.
=> Fix random failure in BulkCopyColumnMapping test

src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementCancellationTest.java
=> test statement.cancel() works when MultiSubnetFailover is set to true

src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
added last test class for statement unit test.
=> Added another test file for Statement test

src/test/java/com/microsoft/sqlserver/jdbc/fips/FipsTest.java
Observed failures because of not handling  propertly for database.
Observe similar problem with user. Added code for port / portnumber
parameter.
=> Fixed local test failures.

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> add socket timeout exception as cause

pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/PoolingTest.java
=> Executor service instead of thread

src/test/java/com/microsoft/sqlserver/jdbc/connection/PoolingTest.java
we are commenting assertion check of countTimeoutThreads()  due to AppVeyor failures. We will investigate this later. 
>  // assertTrue(countTimeoutThreads() >= 1, "Timeout timer is missing.");
=> comment out countTimeoutThreads() due to AppVeyor failures

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java
There are a few easy to fix typos in SQLServerConnectionPoolProxy.
=> Typos in SQLServerConnectionPoolProxy

src/samples/README.md, src/samples/constrained/pom.xml, src/samples/constrained/src/main/java/ConstrainedSample.java
Sample of how to connect with Kerberos constrained delegation using an
impersonated credential
=> ADDED constrained delegation connection sample

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java
=> remove java.io.Serializable interface from SQLServerConnectionPoolProxy.

src/test/java/com/microsoft/sqlserver/jdbc/parametermetadata/ParameterMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
Replace DROP TABLE IF EXISTS calls for compatibility with pre-2016 servers. ( Issue #214 )
=> Fix test failures on pre-2016 servers

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/parametermetadata/ParameterMetaDataTest.java
=> fix SQLServerException wrapped by another SQLServerException

src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
due to random lock timeout failure on AppVeyor. Will investigate later.
=> disabled testRowError 

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataColumn.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPNumericTest.java
=> Tvp precision fix

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/ConnectionDriverTest.java
=> re-interrupt the current thread, in order to restore the thread's interrupt status.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
=> retrieve paramater encryption metadata if they are not retrieved yet

pom.xml
Added OSGI Headers in Manifest.MF For Issue #24
=> Added OSGI Headers in Manifest.MF

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBlob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerJdbc41.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerJdbc42.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPooledConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSetMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java
The current codebase supports JDBC 4.1 and JDBC 4.2 specifications.
This means that there is no need to check if the driver supports JDBC
4.1 and lower since 4.1 is the earliest JDBC version implemented by the
driver. Therefore the methods in DriverJDBCVersion checkSupportsJDBC4
and checkSupportsJDBC41 are obsolete and can safely be removed.
Closes #61
=> Remove obsolete methods from DriverJDBCVersion

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/KeyStoreProviderCommon.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerADAL4JUtils.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionAzureKeyVaultProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/exception/ExceptionTest.java, src/test/java/com/microsoft/sqlserver/testframework/Utils.java
=> have cause of SQLServerException exception at any place where it possible

src/main/java/com/microsoft/sqlserver/jdbc/KerbAuthentication.java, src/main/java/com/microsoft/sqlserver/jdbc/KerbCallback.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
This closes #66 
This patch allow to authenticate using kerberos using the previous
methods (eg: keytab) or specifying user/password either in properties
or in connect method.
This allows to use GUIs for instance to connect using Kerberos without
having a sql user.
If fixes issue #66
=> Allow authenticating using Kerberos and a Principal/Password.

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java
This is essential to minimize the effects of network partition events.
Related to #72 and #85.
=> Support Connection get/setNetworkTimeout().

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBlob.java, src/test/java/com/microsoft/sqlserver/testframework/DBCoercion.java
Fixed simple missing this that cause not assigned type member
=> Fixed missing this -> wrong semantics

src/main/java/com/microsoft/sqlserver/jdbc/KerbAuthentication.java, src/main/java/com/microsoft/sqlserver/jdbc/dns/DNSKerberosLocator.java, src/main/java/com/microsoft/sqlserver/jdbc/dns/DNSRecordSRV.java, src/main/java/com/microsoft/sqlserver/jdbc/dns/DNSUtilities.java, src/test/java/com/microsoft/sqlserver/jdbc/dns/DNSRealmsTest.java
The original driver only computes the SPN without its REALM. That is why the driver
fails in a cross-domain authentication (ex: user@REALM1 try to log on server@REALM2
while REALM2 and REALM1 are in trust).
This commit solves this by trying to compute the REALM when REALM has not been
provided in the SPN. Which includes both generated SPN and User-Provided SPN.
It also enable Kerberos authentication when only IP is provided as long as reverse
DNS are present since when SPN is provided, and REALM lookup did fail, it will
also try with canonical name and if it works, override the hostname in SPN (feature
not activated when user did provide an SPN)
See Issue 36: https://github.com/Microsoft/mssql-jdbc/issues/36
This fixes #36
=> Added automatic detection of REALM in SPN needed for Cross Domain authentication.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java
For every XAResource, initialize the TM by calling xa_open_entry
=> Initialize TM for XAResource

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPResultSetCursorTest.java
=> Tvp server cursor fix

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPTypes.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPTypesTest.java
Also longnvarchar, sqlxml, image
=> added support for max types for TVP

src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java
remove JNI method for ActiveDirectoryPassword Authentication, since we no longer use DLL for ActiveDirectoryPassword authentication
=> remove JNI method for ActiveDirectoryPassword Authentication

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
as be mentioned by @mrotteveel as well on this [page](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setNetworkTimeout(java.util.concurrent.Executor,%20int)), setNetworkTimeout method needs to check for permission.
=> setNetworkTimeout checks for SQLPermission before proceeding

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyResultSetCursorTest.java
=> fix bulk copy cursor issue

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/ThreePartName.java
This patch splits out ThreePartNamesParser (inner class of SQLServerCallableStatement) into a separate class. Internally, that new class caches the regex Pattern for parsing procedure identifiers (ex: database.owner.proc).
The old code (that this replaces) compiles the regex for each new statement.
The code for the new class has been mostly copied from the previous inline implementation. The only changes are:
* Reordering the properties to match their logical order (database / owner / procedure)
* Changing the property values of the parsed object to be final
* Renaming the parsing function to be a static function named "parse"
The implementation of `ThreePartName` itself is copied wholesale from the prior code.
The second commit simply renames the `translator` variable (done in two …
=> Split out ThreePartNamesParser and cache compiled regex Pattern

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ImpISQLServerBulkRecord_IssuesTest.java
Fixes #280 
For issue #280 also mentioned here. https://github.com/Microsoft/mssql-jdbc/issues/161#issuecomment-295906312
Passing smalldatetime via ISQLBulkRecord without specifiying precision should work. 
Also sending out of range values for character type and binary type should throw proper error rather than `Received an invalid column length from the bcp client for colid 1`.
=> For invalid error message by passing smalldatetime in ISQLBulkRecord

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
instead of illegal argument exception.
IOBuffer changes only has a try-catch added that shows big diff.
Also, changed the error message id of R_BulkCSVDataSchemaMismatch ro R_CSVDataSchemaMismatch so it could be used both for Bulkcopy and TVP.
=> Throw SQLServer exception in case of invalid value for TVP

src/main/java/com/microsoft/sqlserver/jdbc/Util.java
FIPS property trustStorePassword was being logged
=> Fix password logging

src/main/java/com/microsoft/sqlserver/jdbc/TVP.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPIssuesTest.java
=> Tvp time 4 fix rtw

.travis.yml
=> Cache mvn dependancies for Travis-CI

appveyor.yml
This is done to speed up builds
=> Caching mvn dependencies for Appveyor

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatementColumnEncryptionSetting.java, src/main/java/microsoft/sql/Types.java
Java offers two kinds of multi line comments /** and /*.
The first is called Javadoc and ends up in generated API documentation
and is displayed by IDEs. The second is a multi line comment that does
not show up.
There are several places there /* instead of /** is used for API
documentation.
[1] https://stackoverflow.com/questions/29815636/and-in-java-comments
[2] http://javadude.com/articles/comments.html
=> Use Javadoc for API documentation

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
=> Get local host name before opening TDSChannel

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
UTC is an enum with one constant and a static variable. It has the
following comment
> The enum type delays initialization until first use.
This is demonstrably wrong.
The static variable is initialized when the class is initialized. If we
look at the decompiled static initializer of UTC we see that.
```
// access flags 0x8
static <clinit>()V
L0
LINENUMBER 522 L0
NEW com/microsoft/sqlserver/jdbc/UTC
DUP
LDC "INSTANCE"
ICONST_0
INVOKESPECIAL com/microsoft/sqlserver/jdbc/UTC.<init> (Ljava/lang/String;I)V
PUTSTATIC com/microsoft/sqlserver/jdbc/UTC.INSTANCE : Lcom/microsoft/sqlserver/jdbc/UTC;
ICONST_1
ANEWARRAY com/microsoft/sqlserver/jdbc/UTC
DUP
ICONST_0
GETSTATIC com/microsoft/sqlserver/jdbc/UTC.INSTANCE : Lcom/microsoft/sqlserver/jdbc/UTC;
AASTORE
PUTSTATIC …
```
=> UTC should be a class

pom.xml
re-create PR for #327 to RTW branch
=> validates javadoc for every commit

src/main/java/com/microsoft/sqlserver/jdbc/Util.java
Per comment in issue #166  from @brettwooldridge from his speedify branch. Try to get this into RTW.
=> Performance fix from @brettwooldridge

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PQImpsTest.java
fix an existing bug when getting parameter metadata and column name has end comment mark and space. Better to merge this PR as soon as possible.
=> String index out of range parameter metadata

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java
=> Make SQLServerException constructors public

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
revert: Makes sure we dont call getParameterEncryptionMetadata more than once d6d7b6c6a74ebb61ea3ec18c4cdf8100d5846154
=> revert another commit

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/RegressionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
=> fix for queries without parameters using preparedStatement

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java
With the newest maven version, they check for the javadoc syntax more rigorously. Made changes to reflect this new maven behavior.
=> simple javadoc fix for accomodating the newst maven version

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionAzureKeyVaultProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
using toLowerCase() without any locale makes it implicitly toLowerCase(Locale.getDefault()). This is fine in most counties but in Turkey, the default locale converts uppercase "I" to a dotless "i", which is not the same as the lowercase "i" in English. Passing Locale.ENGLISH (or Locale.US) in toLowerCase() solves this problem. I have made these changes to all the applicable places in the codebase.
Fixes issue #381
=> Adding locale fix for turkey locale issue when lowercasing an "i"

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PQImpsTest.java
new PR equivalent to #350 which fixes #343
the original way of using Set fmtonly on does not work with complex query or multiple tables. This PR uses a workaround by using LEFT JOIN query.
What the PR does is, converting the original query to a LEFT JOIN query and retrieve parameter metadata.
=> Set fmtonly on to support complex query

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/parametermetadata/ParameterMetaDataWhiteSpaceTest.java
new PR equivalent to #351 which fixes #344
=> Fix parameter meta data with whitespace characters

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/test/java/com/microsoft/sqlserver/jdbc/UtilTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
The optional ResultSet#getObject(int, Class) and
ResultSet#getObject(String, Class) methods are currently not
implemented.
Besides the conversions mentioned in appendix Appendix B, Table B-3 we
also support uniqueidentifier <-> UUID.
This commit does not include support for JSR-310 data types in order to
keep it smaller.
Fixes #6
=> Implement ResultSet.getObject(int/String, Class)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/parametermetadata/ParameterMetaDataTest.java
fix an error on parameter metadata with SQL Server 2008 when calling insertion and parameter name contains braces
=> Fix parameter metadata

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithNullTest.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/RegressionTest.java
Fixes issue #375 and issue #374
=> Meta data caching batch query issue

CHANGELOG.md, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java
Documentation changes for 6.3.0 release.
=> 6.3.0 release doc changes

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java
missed this during code review and saw this later when doing another implementation.
This does not break anything, just improper way to use enum
=> fix an small issue with SQL Variant

pom.xml
give option to user to skip certain tests base on tags. (revised base on PR #114 )
For example, running the following command to build the driver will skip tests that are tagged as `slow`:
```
mvn clean install -Pbuild42 -DskipTestTag=slow
```
If `-DskipTestTag` is not provided in the command, all tests will be executed.
***Will need to update ReadMe after next release.***
=> Give option to skip certian tests base on Tag

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
=> Get string issue for uniqueidentifier

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> remove volatile keyword

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java
Close all statements in the driver that are initialized locally but are never / sometimes not closed.
Fixes issue #308.
=> Fixes all statement leaks in the driver.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
The driver has a workaround for intermittent TLSv1.2 failure. The workaround does not check if the passed in `loginTimeout` is `0`. This PR sets the `loginTimeout` to default( 15 seconds ) in case of a zero value, as specified [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties).
=> Set the loginTimeout to default in case of a zero value - DRIVER_ERROR_INTERMITTENT_TLS_FAILED

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/SQLVariantResultSetTest.java
=> sql_variant issue with String type

src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ISQLServerBulkRecordIssuesTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/ConnectionDriverTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/TimeoutTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
providing `-DskipTestTag=slow` will skip these tests.
=> Skip long running tests

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/KerbCallback.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamColInfo.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamTabName.java, src/main/java/com/microsoft/sqlserver/jdbc/TVP.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/main/java/mssql/googlecode/concurrentlinkedhashmap/Weighers.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/ConnectionDriverTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/lobs/lobsTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/RegressionTest.java, src/test/java/com/microsoft/sqlserver/testframework/DBCoercion.java, src/test/java/com/microsoft/sqlserver/testframework/DBItems.java, src/test/java/com/microsoft/sqlserver/testframework/Utils.java
This increases the overall readability of the code, and has been supported since Java 5.
=> Replace for and while loops with foeach loops

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchTriggerTest.java
Fixes #457 . In case of batch updates, driver hides the custom trigger error messages.
=> Throw the initial batchException 

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataForeignKeyTest.java
fix issue #467
This PR creates 2 temporary tables to store resultsets returned from `sp_fkeys` and `sys.foreign_keys`, then uses ***RIGHT JOIN operation*** and ***UPDATE operation*** to correct and return the values for `DELETE_RULE` and `UPDATE_RULE`.
This is the best solution I can think of in term of performance and memorization. ***Please let me know if you have any better ideas or suggestions***
=> fix methods that use sp_fkeys

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/microsoft/sql/DateTimeOffset.java, src/main/java/microsoft/sql/Types.java
All objects in Java implicity extend `java.lang.Object` so `extends Object` is redundant.
Removing it will reduce confusion, and increase code readability.
=> Remove explicit extends object

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionCertificateStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamColInfo.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamColumns.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamError.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamInfo.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamLoginAck.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamRetStatus.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamRetValue.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamSSPI.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamTabName.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
Removes redundant if/else statements. For example:
```
if (foo()) {
return true;
} else {
return false;
}
```
can be simplified to:
```
return foo();
```
=> Remove redundant if/else statements

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamTabName.java
`return;` is unnecessary if it is the last statement in a `void` method
=> Remove unnecessary return statements

src/main/java/com/microsoft/sqlserver/jdbc/AE.java, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java
|Example|Replacement|
|-|-|
|`condition ? true : false`|`condition`|
|`condition ? false : true`|`!condition`|
|`value == null ? null : value`|`value`|
|`result != 0 ? result : 0`|`result`|
|`a == b ? a : b`|`b`|
=> Simplify overly complex boolean expressions

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/FailOverInfo.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSourceObjectFactory.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSQLXML.java, src/main/java/com/microsoft/sqlserver/jdbc/SqlVariant.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java
Reverts this to open the pr in the JDBC 4.3 branch
=> Revert "Removing deprecated APIs in java 9"

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionCertificateStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamColInfo.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamColumns.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamError.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamInfo.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamLoginAck.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamRetStatus.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamRetValue.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamSSPI.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamTabName.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
Reverting this pr as it caused issues in our internal testing.
=> Revert "Remove redundant if/else statements"

.travis.yml
Updating travis CI build script to use tag `:2017-latest` of docker image mssql-server-Linux.
=> Update travis CI build script

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Calling toString() on a String object is redundant
=> Remove redundant String.toString()

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
When passing parameters to a CallableStatement by name, recognize names that start with '@' as reported by `DatabaseMetaData#getProcedureColumns`.
(ref: Stack Overflow question [here](https://stackoverflow.com/q/46294187/2144390))
=> recognize CallableStatement parameter names with leading '@'

.travis.yml, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/AESetup.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/JDBCEncryptionDecryptionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/PrecisionScaleTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyAllTypes.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyColumnMappingTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyISQLServerBulkRecordTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyResultSetCursorTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestSetUp.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestUtil.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTimeoutTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ISQLServerBulkRecordIssuesTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bvt/bvtTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bvt/bvtTestSetup.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/ConnectionDriverTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/DBMetadataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/NativeMSSQLDataSourceTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/PoolingTest.java, src/test/java/com/microsoft/sqlserver/testframework/DBConnection.java, src/test/java/com/microsoft/sqlserver/testframework/DBResultSet.java, src/test/java/com/microsoft/sqlserver/testframework/DBStatement.java
**Improvements in JUnit Tests:**
`try-with-resources` is available since Java 7 and must be used for defining closeable class objects eg, Connection, Statement, PreparedStatement, ResultSet, Streams, etc. It not only reduces code length, but ensures closure of objects preventing object leaks and also improves code readability. It doesn't make much impact on performance, but prevents memory leaks. 
- A few class level connection and statement objects have been removed as they were being initialized in all class functions. 
- Statement objects are passed in a few functions instead of using class variables to maintain encapsulation.
- `try-with-resources` is avoided in places where connection and statement objects need not be re-initialized and can be reused in a single class. _(A few …
=> Try with resources implementation in JUnit FW - Part 1

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/main/java/com/microsoft/sqlserver/jdbc/TVP.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/TVPWithSqlVariantTest.java
Addresses issue https://github.com/Microsoft/mssql-jdbc/issues/497.
=> Fix creating SQLServerDataTable being O(n^2) issue

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
Running a query that uses a timer can cause an IllegalThreadStateException if the underlying ThreadGroup has been destroyed.
This error happens when the caller executes a query with a timeout and then doesn't execute another query with a timeout until some time has elapsed. The JVM can destroy the ThreadGroup behind the TimeoutTimer (because it contains no active threads) which causes any new query with a timeout to throw an IllegalThreadStateException.
Once the JDBC driver has entered this state any new query with a timeout will throw the exception. It's especially easy to run into this problem in demanding / multi-threaded applications.
My change makes sure the ThreadGroup is not destroyed before creating a new timer thread. If the ThreadGroup is destroyed, the code will create a new …
=> Query with timer can throw IllegalThreadStateException

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy42Helper.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java
Replace bare literals with magic constants. For example:
`cal.set(1, 1, 577738, 0, 0, 0);`
becomes
`cal.set(1, Calendar.FEBRUARY, 577738, 0, 0, 0);`
=> Replace bare literals

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
Replace manual array copying with System.arraycopy().
=> Replace manual array copy

pom.xml
with the updated pom file,
`mvn install -Pbuild41` builds jar, source.jar, javadoc.jar as version `x.x.x.jre7-xxxxx`
`mvn install -Pbuild42` builds jar, source.jar, javadoc.jar as version `x.x.x.jre8-xxxxx`
no longer needs to change version manually for maven releases
=> revise the way that pom file uses version number

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerNClob.java
Fixes issue #186.
This change makes logger in abstract class 'SQLServerClobBase' non-static but final such that it is instantiated for every new object, based on subclass been used to create object and is immutable.
=> Fix for static logger member in abstract class 'SQLServerClobBase'

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java
This PR fixes customer issue #483 by throwing exception if Account locked Exception 18486 found.
=> Throw exception for "Account Locked" SQL Exception 18486

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
also added tests to verify the number of insertion/update executed.
=> Fix prepared statement metadata cache issue

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java
=> Add check for deleted rows in resultsets for scrollable & updatable resultsets

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerNClob.java
Making this change as per discussion and reviews on #537 - fixes #186 
@marschall Appreciate your reviews and feedback on this PR.
=> Adding static loggers back to sub classes for avoiding logger lookup

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
the static modifier was causing concurrency issues during stress testing. the hostname change is for sending a clearer message.
=> Stress test changes

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/SSLProtocolTest.java
remaking this to push against jdbc 4.3 branch for bamboo testing.
=> & is not allowed in error strings or parsing fails.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
After merging this pr, the default behavior of the driver would be to send Time as time. 
Reference for the current behavior in [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/configuring-how-java-sql-time-values-are-sent-to-the-server).
Will fix issue #559
=> update sendTimeAsDateTime default property to false.

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSetMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SqlVariant.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
=> sonarQube fixes

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
race condition where 2 onRequestComplete() executed and the first one set the value to true before the second one evaluated. place tests inside synchronized to fix.
=> fixed random assertion error

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
- Added APIs for disableStatementPooling
- Set the disableStatementPooling to true by default
- Disable prepared statement caching by default 
- Introduce retry logic for missing handle exception. 
Fixes issue #610
=> Re-introduce Retry logic for prepared statement caching 

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/test/java/com/microsoft/sqlserver/testframework/util/ComparisonUtil.java
Added additional information to the error messages causing "Unexpected Big Int Value". Also added fall-through logic to deal with issue #608.
=> Unexpected error message

src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java
Workaround for #624.
Currently, when inserting empty string or `null` into encrypted variable-length columns, the driver sets the data length to `0` and the type to `type(0)` (`varchar(0)` for example). The workaround is to set the length to 1 and the type to type(1).
=> Fix for issue when attempting to insert an empty or null value on encrypted column

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSpatialDatatype.java
Removing unused imports from SQLServerSpatialDatatype.
=> Removing unused imports

README.md
Also updating a couple of old MSDN links.
=> Adding release roadmap and standards info

src/main/java/com/microsoft/sqlserver/jdbc/Geography.java, src/main/java/com/microsoft/sqlserver/jdbc/Geometry.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSetMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/SQLServerSpatialDatatypeTest.java
Fixes issue #655. Also added test cases for it.
Also removed an unused import from Geometry/Geography classes.
=> 655 Fix to return correct column type for spatial datatypes

src/main/java/com/microsoft/sqlserver/jdbc/tdsparser.java
#661.
The fix is to Ignore the column metadata in  `connectionCommand()`, because execution plan information is returned when SHOWPLAN is ON.
=> Fix for the issue when using setMaxRows() with SHOWPLAN ON

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
Fix for both #144 and #645 .This PR reverts #160.
Switching from SocketChannels to Sockets to avoid creating 2 connections when multiSubnetFailover=true.
=> Use Socket instead of SocketChannel when multiSubnetFailover=true

pom.xml
Maven Dependencies Updated:
com.zaxxer » HikariCP - **3.0.0**
org.junit.jupiter » junit-jupiter-api - **5.1.1**
org.junit.jupiter » junit-jupiter-engine - **5.1.1**
org.junit.platform » junit-platform-console - **1.1.1**
org.junit.platform » junit-platform-commons - **1.1.1**
org.junit.platform » junit-platform-engine - **1.1.1**
org.junit.platform » junit-platform-launcher - **1.1.1**
org.junit.platform » junit-platform-runner - **1.1.1**
org.junit.platform » junit-platform-surefire-provider - **1.1.1**
=> Update Maven Dependencies for test suite

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSetMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
According to JDBC specs (15.2.5) - `ResultSetMetaData` instances that were created by a `ResultSet` that has been closed are still accessible. Removing `checkClosed()` from `SQLServerResultSetMetaData`. Fix for #678.
=> Make ResultSetMetaData accessible when ResultSet is closed

pom.xml
Updates the following Maven dependencies/plugins:
_Feature Dependency:_
com.microsoft.azure » adal4j - **1.5.0** - Tested and Verified
_[Also tested with PR #675 which shall be merged in future]_
_Test Dependencies:_
com.zaxxer » HikariCP - **3.1.0**
org.junit.jupiter » junit-jupiter-api - **5.2.0**
org.junit.jupiter » junit-jupiter-engine - **5.2.0**
org.junit.platform » junit-platform-console - **1.2.0**
org.junit.platform » junit-platform-commons - **1.2.0**
org.junit.platform » junit-platform-engine - **1.2.0**
org.junit.platform » junit-platform-launcher - **1.2.0**
org.junit.platform » junit-platform-runner - **1.2.0**
org.junit.platform » junit-platform-surefire-provider - **1.2.0**
_Maven Plugins:_
org.apache.felix » maven-bundle-plugin - **3.4.0**
org.apache.maven.plugins » …
=> Updating multiple Maven Dependency and Plugin versions. 

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PQImpsTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlDecimal.java, src/test/java/com/microsoft/sqlserver/testframework/sqlType/SqlTypeValue.java
Fix for issue #683.
Issue occurs when BigDecimal value is created from double [`e.g. new BigDecimal(5.55)`] or as it is exceeds in Precision than maxAllowedPrecision (38) in SQL Server, and no scale is passed from Client. The driver in this case fails to round off digits and passes BigDecimal value as String, which when received by SQL Server fails with Exception:
`com.microsoft.sqlserver.jdbc.SQLServerException: Error converting data type nvarchar to decimal.`
This fix makes sure BigDecimal values passed to SQL Server are within precision limits and scaled accordingly.
=> Fixes issue with PreparedStatement.setBigDecimal() in the driver when no scale is passed

build.gradle
Gradle Script updated with full support of building driver (jre8 and jre9 version)
=> Update Gradle Script for building JDBC Driver

CHANGELOG.md, README.md, build.gradle, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java
Also updated Gradle / adal4j dependencies as well.
=> Usual changes for preview release 6.5.2

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java
Currently the driver marks computed columns as `SS_IS_COMPUTED`, which violates JDBC spec. Renaming the field to `IS_GENERATEDCOLUMN`.  Fix for #600.
=> Mark computed columns as IS_GENERATEDCOLUMN in the result set returned by getColumns()

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java
Fixing some of the Javadoc warnings. The rest of the issues will be addressed later.
=> Fix some of the Javadoc warnings

src/test/java/com/microsoft/sqlserver/testframework/DBResultSet.java
Turns on data comparison.
Fixed intermittent issues.
=> Enable verify data

src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java
The goal is to make the build fail if there are new public non-static methods in SQLServerConnection and notify the developer to decide whether it needs to be handled by beginRequest()/endRequest().
=> Adding a new test for beginRequest()/endRequest()

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java
Bug fixes, no functional changes.
=> Fixes for issues reported by static analysis tools (SonarQube + Fortify)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
As for the error messages, I am throwing an illegalArgumentException but it gets caught and gets turned into a logging message, so this part doesn't need translation into other languages.
=> Disallow non-parameterized queries for Bulk Copy API for batch insert

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerAeadAes256CbcHmac256Algorithm.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionJavaKeyStoreProvider.java
Fixed an issue where the logger was needlessly traversing the stack to obtain method name.
=> Degradation fix for column encryption enabled (AE)

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/test/java/com/microsoft/sqlserver/jdbc/UtilTest.java
Hello, I'm using mssql-jdbc driver for long time and profiling my application for 20 minutes I found that TDSChannel.read() is taking around 548297 milliseconds of CPU (I guess it's due to synchronization). However improving readLong method I reduced around 30000 milliseconds of pure CPU usage.
Could you merge this small change, please?
=> Improve performance of readLong function unrolling loop and using bitwise operators instead of additions

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java
Issue #744 - support for rs.getObject(n, java.time.LocalDateTime.class)
=> Add support for LocalDate, LocalTime and LocalDateTime to be passed as 'type' in ResultSet.getObject()

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java
As of now JDBC driver does not capture any warnings after ResultSet is fully consumed and the TDS_MSG tokens are not consumed but are left unused in Stream.
Use Case:
Capturing warnings at the end of ResultSet is helpful for PolyBase External Data tables where rows could get rejected due to bad column values. This information is sent by SQL Server after ResultSet data.
=> Changes to read SQL Warnings after ResultSet is read completely

issue_template.md
I made a few minor changes to the template. Please let me know if you have any other suggestions.
=> Updating the issue template 

CHANGELOG.md, README.md, build.gradle, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionJavaKeyStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSpatialDatatype.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java
- Updates changelog and version number
- Formats driver source code for release
=> Update changelog for v7.1.0 preview release

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java
1. Removing the catch block, because the driver should not blindly send attention **packets**. To cancel a query, attention **packets** should only be sent if the client has already sent a request, which has the last packet with EOM bit (0x01) set in status. If a complete request has not been sent to the server, the driver  MUST send the next packet with **both ignore bit (0x02) and EOM bit (0x01)** set in the status to cancel the request (2.2.1.7 of TDS Technical Documentation). This is already properly handled in `IOBuffer.execute()`, which is the only method that calls `doInsertBulk()`. 
2. Adding `this.tdsMessageType == TDS.PKT_BULK`, because prior to `TDS.PKT_BULK`, the driver has already sent `INSERT BULK` SQL statement to the server, which in case of an exception needs to be …
=> Fixed issues in BulkCopy exception handling

.travis.yml
Jdk 10 no longer supported by oracle.
=> Update JDK to 'oraclejdk11' for Travis CI

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java
An `Exception` may have a `null` error message.
=> Fixed potential NullPointerException in logException()

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
- Replace string concatenation w/ StringBuilder in loops
- Avoid string concatenation in `StringBuilder.append()`
=> Fix/improve StringBuilder usages

src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPAllTypesTest.java
Test fails randomly due to shared objects in tests which get closed due to race conditions. 
This PR makes sure Connection and Statement are always dedicated and open while executing a single test.
=> Change scope of Connection/Statement in test to prevent random failures

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Fixed issue #872.
Currently, when we call setAutoCommit(), we execute this query:
```
IF @@TRANCOUNT > 0 COMMIT TRAN set implicit_transactions off 
```
This still leaves a transaction open in Azure DW, according to MSDN documents.
To fix this issue, we're going to execute this query instead:
```
set implicit_transactions off IF @@TRANCOUNT > 0 COMMIT TRAN 
```
Which should do the same thing except it fixes the aforementioned issue in Azure DW.
=> Fix issue with setAutoCommit leaving a transaction behind in Azure DW

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java
wasNull() does not actually move the cursor, and it's unnecessary to populate the active lob objects when it's called. Addresses #867.
=> Fix | Removed populating Lobs when calling wasNull()

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
Intermittent TLS1.2 issue details can be found [here](https://blogs.msdn.microsoft.com/dataaccesstechnologies/2016/11/30/intermittent-jdbc-connectivity-issue-the-driver-could-not-establish-a-secure-connection-to-sql-server-by-using-secure-sockets-layer-ssl-encryption-error-sql-server-returned-an-incomplete-respons/). 
- Based on the discussion on #879 , changed the retry logic to also check for Exception cause because actual error message can be wrapped into a different message when re-thrown from underlying `InputStream`.
- Some minor cleanup.
=> Improved retry logic for intermittent TLS1.2 issue

src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyColumnMappingTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyISQLServerBulkRecordTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyTestUtil.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/BulkCopyWithSqlVariantTest.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/TVPWithSqlVariantTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fips/FipsEnvTest.java
removed/addressed/created backlog on TODOs
=> Address TODOs in tests

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerMetaData.java
=> Add SQLServerMetadata constructor to set precision for string types

src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
Self-explanatory. Moved some error messages to the TestResources file.
=> Remove hardcoded error messages from test file

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/microsoft/sql/DateTimeOffset.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java
As `PreparedStatement.setObject(int, Object)` already supports `java.time.OffsetDateTime`, it may make sense.
This was proposed in https://github.com/Microsoft/mssql-jdbc/pull/749#issuecomment-405637052 , but no work has been done, it seems.
=> Add support for OffsetDateTime to be passed as 'type' in ResultSet.getObject()

README.md, src/main/java/com/microsoft/sqlserver/jdbc/ActivityCorrelator.java, src/main/java/com/microsoft/sqlserver/jdbc/FailOverMapSingleton.java, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/PLPInputStream.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBlob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerNClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSQLXML.java, src/main/java/com/microsoft/sqlserver/jdbc/osgi/SQLServerDataSourceFactory.java
Add a flag to XML transformer factory
=> Fix | Security Issue specified by sonarqube

src/main/java/com/microsoft/sqlserver/jdbc/TVP.java
=> Fix | Handle Null resources in TVP to avoid NullPointerException

src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java
Changed a thread used to initialize `ScheduledThreadPoolExecutor` to daemon so the JVM can exit in specific bulkcopy scenarios.
=> Fix | ThreadPoolExecutor thread preventing JVM from exiting

src/main/java/com/microsoft/sqlserver/jdbc/ParameterUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/RegressionTest.java
=> Fix | Fixes regression caused in SQL Parser

src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
We don't need to rely on the column number to verify the test.
=> Fix issue with JUnit test with Unix environment

src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPResultSetCursorTest.java
Was causing random failures.
Tested all variations (6 total) for 1000 iterations each. `testMultiplePreparedStatementAndResultSet` (test with error from logs) was additionally tested for 10,000 iterations.
=> Fix | Ordered selects on TVP tests

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java, src/test/java/com/microsoft/sqlserver/jdbc/exception/ErrorStateTest.java
Fixes #956 
Calling `SQLException.getErrorState()` would result in SQL State of length more than 5 characters allowed as per [SQL State Specifications](https://en.wikipedia.org/wiki/SQLSTATE). This fix restricts length of SQLException Error State and appends zeroes (0) as needed to Error State received from SQL Server.
As per SQL Server specifications, the values of [ERROR_STATE](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-state-transact-sql?view=sql-server-2017#return-value) ranges from 0 - 255 as one can raise an error with custom Error State using [RAISEERROR](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql?view=sql-server-2017) as well. Accordingly, we must adjust trailing zeroes to the SQLException Error State.
=> Fix | Fix SQL Exception Error State length to respect SQLSTATE Standards

azure-pipelines.yml, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/ConnectionDriverTest.java
Fixes #954 
- Create `SQLServerStatement` in try-with-resources block.
=> Fix | Fix possible Statement Leak in SQLServerConnection.isValid() API

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
=> Refactor SELECT_METHOD in SQLServerConnection

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
=> Fix SQLServerConnection documentation

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DataTypesTest.java
Starting from SQL Server 2016, the rounding logic for inserting datetime value has been changed. Instead of uniformly rounding up values normally (<=4 rounds down, >=5 rounds up), the logic present in the getRoundedMilliseconds method shows how the numbers are actually rounded.
The writeRPCDateTime method that gets used during updating a datetimecolumn wasn't correctly reflecting this, and this PR addresses that issue.
=> Fix for updating datetime value

pom.xml, src/main/java/mssql/googlecode/concurrentlinkedhashmap/Linked.java, src/main/java/mssql/googlecode/concurrentlinkedhashmap/LinkedDeque.java
This PR changes the way we generate Javadocs for the driver.
It now excludes generating Javadocs for `mssql.googlecode` packages as they are not exported with driver Jars. Javadocs for future versions will look as under:
=> Maven | Exclude non-exported packages from Javadocs

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
As per [Java Specifications](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#abort(java.util.concurrent.Executor)), executing `Connection.abort(Executor executor)`, must also release all resources and mark the connection closed as `Connection.close()` would.
The PR fixes the same by managing resource cleanup separately in a common internal method.
=> Fix | Fix SQLServerConnection.abort() API behavior to clear resources consistently

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyRowSetTest.java
=> Support FLOAT data type for bulk copy operation using RowSet

src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/SetObjectTest.java
Open for more use-cases to capture any wrong computations done by driver when sending data to SQL Server's DateTimeOffset column.
=> Test | Add test to validate microsoft.sql.DateTimeOffset interchangeable behavior

pom.xml
Fixes Manifest entry `osgi.ee;filter:="(osgi.ee=UNKNOWN)"`
=> Maven | Update Maven Bundle version for newer JDK compatibility

src/main/java/com/microsoft/sqlserver/jdbc/FailOverInfo.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java
formatErrorMsg() from @rene-ye
=> Add formatErrorMsg for comparing error messages in tests

azure-pipelines.yml, build.gradle, pom.xml, src/test/java/com/microsoft/sqlserver/jdbc/JDBC43Test.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/testframework/Constants.java
This PR adds support to build `jre12` Jar for the driver along with `jre11` and `jre8` with both Maven and Gradle build scripts.
=> Feature | Introduce Java 12 Support to driver and build additional "jre12" JAR

src/main/java/com/microsoft/sqlserver/jdbc/DataTypes.java, src/main/java/com/microsoft/sqlserver/jdbc/Geography.java, src/main/java/com/microsoft/sqlserver/jdbc/Geometry.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSpatialDatatype.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/SQLServerSpatialDatatypeTest.java
Addresses issue #1031 and #1038.
For #1031, I changed the isValid bit to be set to `true` by default, as it is stated in the CLR specs. Leaving this isValid bit to false makes some of the Spatial Datatype operations on the server's end fail.
For #1038, I've declared the default constructors as protected, to allow extension of Geometry and Geography classes.
I've also noticed that setObject() using Geography/Geometry weren't working as intended, so I'm fixing that as well.
=> Fix | Mark spatial datatypes as valid

src/main/java/com/microsoft/sqlserver/jdbc/SharedTimer.java
=> Fix | Fix SharedTimer implementation to use class level lock for thread safety

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/TimeoutTest.java
=> Fix | Fix issues with Login Timeout not getting applied appropriately.

src/main/java/com/microsoft/sqlserver/jdbc/DataTypes.java, src/main/java/com/microsoft/sqlserver/jdbc/InternalSpatialDatatype.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerEncryptionType.java, src/samples/adaptive/src/main/java/ReadLargeData.java, src/samples/datatypes/src/main/java/SpatialDataTypes.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/SQLServerDataTableTest.java
Replacing `Enum.values()` calls with static arrays. Fix for #1051
=> Performance | Remove Enum.values() calls to avoid unnecessary array cloning 

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableMixedTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPAllTypesTest.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPIssuesTest.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPNumericTest.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPResultSetCursorTest.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPSchemaTest.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPTypesTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/UTF8SupportTest.java
The PR:
- Fixes Database Metadata tests that expect existing table in target database.
- Fixes Maven build warnings with JavaDocs
- Cleans all remaining database objects in Junit Tests (User Defined Table Types (TVP), Stored Procedures, Scalar Functions)
=>  Test | Fix DB Metadata tests + fix maven warnings + clean all objects

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableMixedTest.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
Fixed an issue where CallableStatement was not setting parameter indexes properly when columns aren't found via column name lookup. This results in the driver returning a misleading error message early instead of executing the statement and receiving the proper message from server. Addresses issue #1059.
=> Fix | Misleading error message in CallableStatement

src/main/java/com/microsoft/sqlserver/jdbc/ParameterUtils.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerFMTQuery.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParser.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/DBMetadataTest.java
Fuzzing caught a few unexpected errors. Most changes are just checking Iterator.hasNext() before moving the iterator.
=> Changes after Fuzz Testing useFmtOnly

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkBatchInsertRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerFMTQuery.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParser.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSpatialDatatype.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java
Transforming from `someString.equals("string")`  to `"string".equals(someString)`. This avoids checking for `null` and also prevents `NullPointerException` being thrown.
These fixes multiple SonarQube violations of the rule: [Strings literals should be placed on the left side when checking for equality](https://rules.sonarsource.com/java/RSPEC-1132)
=> Improvements | String Literals on the left on comparisons (SonarQube)

src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/AESetup.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerDriverTest.java, src/test/java/com/microsoft/sqlserver/testframework/Constants.java
`JAVA_KEY_STORE_PASSWORD` - Not an actual password, but a keyword to use [built-in JDBC keystore provider](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-2017#using-java-key-store-provider).
`TRUST_STORE_PASSWORD` - Not an actual password, but a [connection string keyword.](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-2017)
=> Fix | Rename constants to avoid CredentialScanner false positives

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
As mentioned by @dmitri-blinov on #1075, switching from `startsWith()` to  `charAt()` may lead to an exception in case of an empty string.
=> Fix | Revert chartAt() change

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java
Remove extra spaces to be compliant with https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getNumericFunctions-- and https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getStringFunctions--
fixes #1115
=> Fix | Remove extra spaces in SQLServerDatabaseMetaData.getNumericFunctions()/SQLServerDatabaseMetaData.getStringFunctions() return values (#1117)

src/test/java/com/microsoft/sqlserver/jdbc/ComparisonUtil.java
Failure message should always include the expected/actual values.
Currently, they are added manually in some cases, but it seems to make more sense to use `assertEquals`.
BTW, I noticed that the assertion comparing `java.sql.Date`s only compares `DAY_OF_MONTH`.
Is it intentional?
It was committed in https://github.com/microsoft/mssql-jdbc/commit/115336296d70eb49b6e792aabe621ab8b93dee51#diff-d4cfc7fdd584aa2ec6cec3e2fcaef964R146 .
=> Tests | Improve assertions in ComparisonUtil

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSpatialDatatype.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/SQLServerSpatialDatatypeTest.java
=> Fix STAsBinary returning null for a single point

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
Fixes issue #1136. Added extra test that tests this case as well.
=> Fix SQLServerDatabaseMetada.getColumns not escaping wildcard

azure-pipelines.yml, build.gradle, pom.xml
This PR introduces JAVA 13 support and deprecates jre12 jars.
=> Feature | Introduce JAVA 13 Support

src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerBulkData.java, src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerBulkRecord.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyISQLServerBulkRecordTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ISQLServerBulkRecordIssuesTest.java
The PR also updates Bulk Copy tests to use ISQLServerBulkData instead of ISQLServerBulkRecord.
=> Change | Updated ISQLServerBulkData APIs to throw SQLException

pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerDriverTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyColumnMappingTest.java
=> Fix | Send bulk data as unicode when destination column is nchar/nvarchar

src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java
fixes issue when multiple threads calls AE methods
=> Synchronized native AE calls to DLL

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBlob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerClob.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerNClob.java
Also includes a fix for image columns #1201.
=> Added backwards compatibility for calling Clob#length() on NVarchar columns

azure-pipelines.yml, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/AESetup.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/EnclaveTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/JDBCEncryptionDecryptionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/PrecisionScaleTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/RegressionAlwaysEncryptedTest.java, src/test/java/com/microsoft/sqlserver/jdbc/EnclavePackageTest.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
Added new test property "enclaveServer" to define semicolon delimited list of enclave servers to test AEv2 and updated enclaveAttestationUrl and enclaveAttestionProtocol to support semicolon delimiters as well. Enclave tests will be run against the list of servers using these properties in the same order they are defined.
eg.
enclaveServer=HGS-2K19-01.galaxy.ad;jdbc-aas-sgx.westeurope.cloudapp.azure.com
enclaveAttestationUrl=http://jdbchgsservice.galaxy.ad/Attestation;http://battlestareuwattest.us.attest.azure.net/attest/SgxEnclave?api-version=2018-09-01-preview
enclaveAttestationProtocol=HGS;AAS
=> updated AE tests to test list of enclave servers from config.properties

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DataTypesTest.java
Added a null check to prevent NPE.
Fixes issue #1249.
=> Add null check for getObject() with LocalTime and LocalDate

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionAzureKeyVaultProvider.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java, src/test/java/com/microsoft/sqlserver/testframework/Constants.java
- The driver will read from `mssql-jdbc.properties` file from the current working directory.
- Set `AKVTrustedEndpoints` property to a semicolon-delimeted list. If the value begins with a semicolon, it extends the default list; otherwise, it replaces it.
=> Provide an option to configure trusted Azure Key Vault endpoints

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java
SQL Server Linux is x64-compatible only.
=> Fix | Fixed a warning when retrieving Operating System information from SQL Server Linux

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPNumericTest.java
PR For #1281.
When `SQLServerDataTable` is passed in as an argument to `PreparedStatement.setObject()`, it makes sense to first attempt to get the TVP name from that object, before querying database for metadata.
=> Get TVP name from SQLServerDataTable when using PreparedStatement.setObject()

azure-pipelines.yml, build.gradle, pom.xml
This PR introduces JAVA 14 support and drops jre13 jars.
=> JAVA 14 | Introduce JAVA 14 Support

src/test/java/com/microsoft/sqlserver/jdbc/socketfactory/CustomSocketFactoryTest.java
Connection attempt can be made multiple times depending on the environment (such as URL redirection is involved in the case of the client being inside Azure network), so remove this part of the test.
=> Socket Factory Test Fix

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerVSMEnclaveProvider.java
Explicitly check certificate expiry.
=> Fix | Add certificate expire validation when using Always Encrypted with secure enclaves

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java
Fixes issue #1135.
The format in which the expires_on property is sent to the driver from Azure server used to be in the form of a string, but starting from the latest API version (2019-08-01), this value is now an integer value, which is consistent across all regions and operating systems (Windows/Linux).
Note that this fix only applies to retrieving access tokens for MSI authentication from Azure Functions (and Azure Web Apps), and it doesn't affect the usual Azure IMDS routine for MSI authentication.
=> MSI expiry date format fix for Azure Functions

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Adding an overload of commit() to support delayed durability.  Fixed compilation error.  Didn't add method to ISQLServerConnection interface.  Not sure if that is desirable.
=> Adding Delayed Durability

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java
When driver detects the connection close, it is not returning the correct sql/xopen compliant state. This is causing the connection pool managers like `hikari` to detect a connection closed state correctly. This fixes issue #1325
=> Fix #1325, return correct sql state when connection is closed

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/SQLVariantResultSetTest.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/TVPWithSqlVariantTest.java
Fixes issue #1302.
Even though the code has remained this way for a long time, I think the current behavior of sql_variant is incorrect. The `jdbcType` variable in dtv.java is the JDBC type that the user specifies when they try to retrieve the data. This variable is telling the driver what the user wants to retrieve the data as, but this variable was getting modified to become the base type of the server's column type when retrieving sql_variant data, causing this issue (this effectively ignores the data type that the user was asking to retrieve sql_variant as). Leaving `jdbcType` as it is (which we should, since that's what the user wants) solves the issue.
However, when the driver performs bulk copy on a sql_variant column, the driver does need to designate `jdbcType` as the underlying …
=> Fix issue with cast exception from sql_variant

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
Removes dead code meant for servers before yukon.
=> Remove dead code and clean up legacy code

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/resources/BulkCopyCSVTestInputDelimiterEscape.csv
Fix for #1173 
Adding `SQLServerBulkCSVFileRecord.setEscapeColumnDelimitersCSV`. When set to `true`, the following rules will apply.
- Each field may or may not be enclosed in double quotes.
- If fields are not enclosed with double quotes, then double quotes may not appear inside the fields.
- Fields containing double quotes, and delimiters should be enclosed in double quotes. 
- If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote.
=> Added an option to escape delimiters in CSV files when using bulk copy

src/main/java/com/microsoft/sqlserver/jdbc/Util.java
Just needed the same treatment as in dtv.java:
https://github.com/microsoft/mssql-jdbc/blob/dbb3547960e5f624665bd9b1c4a8a86df653dee0/src/main/java/com/microsoft/sqlserver/jdbc/dtv.java#L1609
In the case where the javaType is String but the JDBCType is Geometry or Geography, we need to handle the data a bit differently. Tests with AE enabled passed, and Maven test passed as well.
=> Fix spatial datatypes cast error when AE is enabled

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
- Modified the query for Azure DW to select 0/1 as YES/NO.
- Improved getColumns() test.
Fix for #1352
=> Fixed an issue with getColumns() not returning correct type for IS_AUTOINCREMENT and IS_GENERATEDCOLUMN against Azure Data Warehouse

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
Implemented a new function to SQLServerDatabaseMetaData to check database compatibility level.
=> Added DatabaseMetaData.getDatabaseCompatabilityLevel

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java
Fixes issue #1363.
This allows ResultSets that are not SQLServerResultSets to not error out on that line.
=> Allow non-MSSQL ResultSets to bulk copy DateTimeOffset

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/PrecisionScaleTest.java
Fixes issue #1301. Testing shows it also fixes #1360, but will need to confirm from user.
Continues from PR #1334. Testing has been carried over, but the fix is different.
The problem was coming from executing `sp_describe_parameter_encryption`. This statement is executed when AE is turned on to retrieve the encryption parameter. Code was currently written in such a way that `sp_describe_paramter_encryption` was being executed twice (or multiple times) if AE was enabled, which caused the driver to think that the current request was completed, which caused the driver to error out during the actual execution of the batch statement (and a plethora of other problems). Adding logic to only run param fetch once and save the encryption metadata for the subsequent batches as well solves this …
=> Fix | Fix batch insert failing when AE is turned on

src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerAASEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerVSMEnclaveProvider.java
Added database name to caching key. The new key format is `serverName` + `databaseName` + `attestationUrl`.
Removed an unused package privatate SQLServerConnection getter `getScatalog()` which returned the same value as the public getter `getCatalog`.
Changed cache key lookup to occur before calling sp_de because doing so after would cause a new connection to call sp_de with 3 parameters which would create another enclave session.
=> Change | Enclave caching key

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ISQLServerBulkRecordIssuesTest.java
Fixes issue #1391.
Straightforward fix, sorts the 'columnOrdinals' object if the returned set happens to be unordered.
=> Fix | Sort column ordinal mapping during bulk copy

build.gradle, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataForeignKeyTest.java
- Fixed Gradle script to use correct fetAuth exclude tag.
- Rename FK to a random name to avoid intermittent failures.
=> Test | Fix Gradle exclude tag and DatabaseMetaDataForeignKeyTest

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyRowSetTest.java
Fixes issue #1414.
We cannot assume that length = number of bytes when destination collation is not equal to null.
=> Fix | Fix bulkcopy failing when inserting non-unicode multibyte String

src/test/java/com/microsoft/sqlserver/jdbc/connection/DBMetadataTest.java
sp_sproc_columns_100 returns all stored procedures that match the criteria. There is a chance that stored procedures which match the criteria are being altered/updated during the test. If we only query for the stored procedure we created in the test by restricting the SP to use the function name, this won't happen as the SP names are unique.
=> Fix | Intermittent deadlock error by querying only the procedure created

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAConnection.java
From PenTest results.
As with other passwords that have been removed from memory, I temporarily add it back for XA connections because XA connections create two connections (one for control connection, one for actual connections), but the outcome is the same in that this password will not remain in memory after the connection has been established.
=> Fix | Remove clientKeyPassword from memory

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/resources/BulkCopyCSVTestInputDelimiterEscape.csv
Fixes #1426 as suggested by @rripley.
=> Fix | SQLServerBulkCSVFileRecord dropping empty trailing columns when escapeDelimiters = true

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
Fixes a bug in SQLServerPreparedStatement.buildExecuteMetaData which
caused the SqlState as returned from the server error to be discarded in
thrown exceptions. The SqlState information is useful for application
level error handling.
No tests are provided, as I can't get the test harness to run in my
local environment. However, here are steps to reproduce the 'bad'
exception with no included SqlState:
```java
Connection conn = null;     // Fill in with SqlServer connection.
conn.prepareStatement("s");
conn.getMetaData();         // Throws exception without SqlState.
```
=> Retain error information in SQLServerPreparedStatement.getMetaData exceptions

src/test/java/com/microsoft/sqlserver/jdbc/MaxResultBufferTest.java
Azure DW does not support cursors.
=> Test | Skip MaxResultBufferTest.testResultSetLinear() against Azure DW

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> Fix | Avoid high mem alloc in TDSWriter#writeReader

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> Fix integer overflow in TDSWriter.writeString()

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Previously it was hard coded to 0.0.0.0.
=> Send the driver version to the database during prelogin

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithNullTest.java
This PR is to port the changes in #1509. 
- Fix issue #1499.
- Fix test failure in `testClearBatch`.
- Add `testClearBatchAEOnConnection` for `columnEncryptionSetting=Enabled` scenario.
=> Fix | Clear batch params when clearing params in pstmt

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/ClientProcessIdTest.java
Since we can easily do it in Java 9 and up, we should. If catching NoClassDefFoundError is objectionable, I'm open to other suggestions.
You can validate the behavior by querying `sys.dm_exec_sessions` when a connection is active:
`select * from sys.dm_exec_sessions`
=> Send client process ID to server on Java 9+

src/test/java/com/microsoft/sqlserver/jdbc/connection/ClientProcessIdTest.java
exclude Azure DW as command is not supported
=> Exclude Azure DW for client PID test

src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecuteWithErrorsTest.java
org.hamcrest classes fails to resolve to module and below module conflict each other:
- org.hamcrest.core
- hamcrest.core
Steps to reproduce:
- Right click and select "Create module-info.java"
- All other classes are resolvable except org.hamcrest classes
If it's not absolutely needed, tests can avoid using these Junit APIs as standard alternatives are available.
=> Avoid using org.hamcrest due to module issues

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
=> Fix memory leak

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java
While using JDBC on Azure SQL Managed Instance it displays a warning while trying to figure out OS architecture.
The warning is:
_Feb 05, 2021 1:19:02 PM com.microsoft.sqlserver.jdbc.SQLServerXAResource DTC_XA_Interface
WARNING:  XAResourceID:1 Cannot retrieve server information: :begin 1, end -1, length 106_
This is a [similar problem](https://github.com/microsoft/mssql-jdbc/issues/1278) resolved earlier for SQL Server in Docker. This PR adds one more check for SQL Azure servers.
=> Fix a warning when retrieving architecture from Microsoft SQL Azure server

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionAzureKeyVaultProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/MultiUserAKVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/RegisterKeyStoreProviderTest.java
- format code
- minor test changes
=> Added check for closed statement to registerColumnEncryptionKeyStoreProvidersOnStatement

src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerError.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerLexer.java
Also fixing some build and javadoc warnings
=> Add 42108 and 42109 to transient errors list

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/ISQLServerBulkRecordIssuesTest.java
When writing a LocalDateTime with bulk copy, the driver may return an error when second-of-minute and nano-of-second is 0:
```
com.microsoft.sqlserver.jdbc.SQLServerException: Conversion failed when converting date and/or time from character string. Msg 241, Level 16, State 1, Conversion failed when converting date and/or time from character string.
```
When time units to the right of the minute are all 0's, the LocalDateTime.toString() will simplify the string format to **uuuu-MM-dd'T'HH:mm**, which SQL Server is not able to process due to the missing seconds. This PR changes the string conversion to use the DateTimeFormatter and ensures that it includes the necessary padding.
For example:
```
LocalDateTime                  = 2021-08-13 00:00:00
Current - toString()           = …
```
=> Fix conversion of LocalDateTime and LocalTime to String in Bulk Copy

pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerLexer.java
=> Update versions to fix vulnerabilities

src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthTest.java
- deprecate AADSecurePrincipalId/AADSecurePrincipalSecret connection properrties and replace with username/password
- remove getAADSecretPrincipalId for security reasons
=> Deprecate and Rename Service principal connection properties

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
To aid in log analysis. I was tempted to log all system properties, but there are some sensitive ones in there, so I targeted the logging to relevant properties.
This is not a requirement to merge. I'm open to discussion. It just seems like this might help when we get issues where people leave out important details.
=> Log the driver version + plat info on connect to aid in log analysis

pom.xml
Bringing back CodeCov with cumulative coverage.
Sample build:
https://sqlclientdrivers.visualstudio.com/public/_build/results?buildId=42396&view=results
Keeping test failures aside, codecov report is now generated:
https://codecov.io/gh/cheenamalhotra/mssql-jdbc/commit/46029f6cbae8a0cb60a00be3970a20385ded419a/build
Once this is merged, I'll trigger report for this repo.
=> Jacoco related updates

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Java's NativeSeedGenerator can sometimes fail on getSeedBytes(). Exact reason is unknown but high system load seems to contribute to likelihood. Retry once to mitigate.
=> Retry randomUUID() to mitigate intermittent java NativeSeedGenerator failure

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
Retrieval of Java8 dates/times with calls such as `rs.getObject(columnIndex, LocalDate.class)` can be made much faster, mostly because many unnecessary allocations are done.
For instance, when a datetime column is read, the convertTemporalToObject function:
1. Creates a new LocalDateTime, which internally creates a new LocalDate and a new LocalTime
2. Adds days, which creates a new LocalDate, wrapped in a new LDT
3. Adds nanos, which after complex computations (mostly useless because it's intraday nanos) creates a new LocalTime, wrapped in a new LDT
That's 7 allocations, when only 3 (or 2 for dates) are really useful.
I've also extended the test to ignore the time component, because I see many cases in the open world were timeless dates are stored in needlessly large types such as …
=> Optimize the retrieval of Java8 dates/times

CHANGELOG.md
Made the changelog changes David suggested.
=> Needed to not use internal acronymns

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCSVFileRecord.java
Java doc updated as per user ask. SQLServerBulkCSVFileRecord now states that regex characters should be escaped.
Fixes #1691
=> Updated javadoc for SQLServerBulkCSVFileRecord

src/test/java/com/microsoft/sqlserver/jdbc/resiliency/BasicConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/PropertyTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ReflectiveTests.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResiliencyUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResultSetsWithResiliencyTest.java
Azure DW engine edition is 10 which is even older than SQL 2012 which is 11.  Idle Connection Resiliency seem to require 12 and above
=> Exclude Idle Connection Resiliency tests on Azure DW

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/SQLVariantResultSetTest.java
=> Support for datetimeoffset sql_variant

src/main/java/com/microsoft/sqlserver/jdbc/SSPIAuthentication.java
Same as https://github.com/microsoft/mssql-jdbc/pull/1688 with additional logging and running formatter.
=> Enable cname resolution when realm is specified in connection

src/main/java/com/microsoft/sqlserver/jdbc/AE.java, src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/IdleConnectionResiliency.java, src/main/java/com/microsoft/sqlserver/jdbc/ParameterUtils.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCertificateUtils.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionJavaKeyStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerMSAL4JUtils.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSQLXML.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSpatialDatatype.java
=> Fix issues detected by SonarQube

src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ErrorMessageTest.java
this test is slow and causes hang in VMs that do not have supported browser
=> Removed interactive auth timeout test

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPooledConnection.java
This will also make sure the traceID is set before used in toString().
The loggername handling seems to be a bit divergent- in some cases a literal package is used in others not. I am not sure if this is intentional, so I left it alone.
Sorry for the removal of trailing whitespaces, but I figured it it generally helpful. If you want me to isolate the changes, please let me know.
Signed-off-by: Bernd Eckenfels <ecki@apache.org>
=> Simplify traceID creation in DataSource and PooledConnection.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthCommon.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthTest.java
After migration from ADAL to MSAL4J, clients were unable to connect to certain endpoints (e.g. Azure Data Explorer). This issue was resolved by the Azure Data Explorer / Kusto team, by allowing another property to be passed into the connection string, changing the authority used when connecting with MSAL4J, and resolving the error.
An Azure Active Directory test was implemented to confirm the workaround does work for JDBC driver, and for authentication using Azure Active Directory username and password. 
Original issue and fix: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/382
--------------------------------------------------------------------------------------------------------------------------------------------
On build, warnings were given regarding …
=> Added Azure Active Directory tests for Azure Data Explorer using user/password/applicationName AND removed deprecated tags to fix build warnings

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
(Update 3/2/2022) While the below approach works, given that the use of `readSkipBytes` has changed, its no longer necessary to pass in a `long`. Thus the changes can be reduced to ensuring all involved types are `int`, avoiding any information loss.
-----------------------------------------------------------------------------------------------------------------------------------------
As seen here: https://github.com/microsoft/mssql-jdbc/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmain, there is an implicit cast taking place in IOBuffer.java, that may lead to a loss of information. The solution was to first check if the long value `bytesToSkip` can be converted without information loss, and only allow addition to `payloadOffset` if this is true.
The reverse, that is widening …
=> Added a check to prevent Implicit narrowing conversion in compound assignment

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Minor change. This check exists for other AD auth cases, but will just throw java.lang.ClassNotFoundException if ActiveDirectoryServicePrincipal is used and MSAL libraries are not in the classpath. In another project, I had spent some time trying to determine the issue, only to notice this missing check would have been helpful.
This just adds the check used in other AD auth cases to the ActiveDirectoryServicePrincipal case.
> Caused by: java.lang.NoClassDefFoundError: com/microsoft/aad/msal4j/IClientCredential
at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5341)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5293)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnecti …
=> Add check for MSAL library when attempting ActiveDirectoryServicePrincipal authentication

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SecureStringUtil.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/BasicConnectionTest.java
This allows storing of the trustStorePassword in encrypted form since it is needed for Idle Connection Resiliency when recovering connections.
=> Add encrypt utility to obfuscate password strings

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
This refactors the usage of `SQLServerColumnEncryptionAzureKeyVaultProvider` into private methods.
This is useful for the native-image compilation GraalVM's optimizations, allowing these methods to be dynamically substituted when the Azure classes are not in the classpath
See https://github.com/quarkusio/quarkus/pull/24010 for more information
=> Refactor SQLServerColumnEncryptionAzureKeyVaultProvider usage in SQLServerConnection

src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
In the previous commit for attestation protocol, the check to assign the correct AE version in SQLServerConnection, 1) mistakenly assigned V1 to all HGS,AAS protocols and 2) assigned V2 to null protocols. By reformatting, the check should now correctly assign version for all cases of attestation URL and protocol.
Also included the version change in SQLJdbcVersion as it was needed to properly test that this fix was working.
=> Formatted the check that assigns AE version to correctly assign version to protocol

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SecureStringUtil.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java, src/test/java/com/microsoft/sqlserver/jdbc/UtilTest.java
Since Strings are immutable in Java and tend to stay around in memory for potential re-use in the JVM, it's best practice to avoid them for sensitive data. It's recommended to use char arrays instead and clear/overwrite them once they're no longer needed. This limits the amount of time sensitive data remains in memory.
=> Avoid String use with secure strings

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamColumns.java, src/main/java/com/microsoft/sqlserver/jdbc/tdsparser.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/DataClassificationTest.java
Fixed an unknown token 0xa3 error when selectMethod cursor is set when used with dataclassification.
=> Fixed dataclassification unknown token error

src/main/java/com/microsoft/sqlserver/jdbc/StreamColumns.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/DataClassificationTest.java
Both SensitivityLabelIndex and InformationTypeIndex have a max of USHORT_MAX as defined in the TDS spec, and not a max of INTEGER_MAX
=> Dataclassification sensitivity max index fix

src/main/java/com/microsoft/sqlserver/jdbc/SecureStringUtil.java, src/test/java/com/microsoft/sqlserver/jdbc/UtilTest.java
Prepend iv onto the encrypted bytes so that each iv is unique and preserved with its encrypted bytes for later decryption.
=> Fix: Initialization vector cannot be reused

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamDone.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/BasicConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/PropertyTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ReflectiveTests.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResiliencyUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResultSetsWithResiliencyTest.java
This fixes #1846 and #1505 where a DONE_ERROR status from the server resulting from a killed session was ignored by the driver.
=> Added check for DONE_ERROR status token and throw appropriate exception

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java
When onDone is reached for a resultset, we need to stop parsing. Since https://github.com/microsoft/mssql-jdbc/pull/1857, we do not need to consume/process the done token because we are instead throwing an exception for a DONE_ERROR
=> Resultset onDone Fix

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
Fixes https://github.com/microsoft/mssql-jdbc/issues/1880
=> Fixed intermittent null prepared statement handle

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
Fixes https://github.com/microsoft/mssql-jdbc/issues/1896
doExecutePreparedStatement() isn't affected because it doesn't execute TDS requests one after the other eg. It doesn't do batching.
=> Fixed query cancellation bug that intermittently occurs in batch queries

pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementCancellationTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
For https://github.com/microsoft/mssql-jdbc/issues/1871
- Fixes callable statement index out of bounds
- Fixes callable statement parameter not defined error
=> Fixed callable statement index out of bounds error; Fixed parameter not defined error

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/RegressionTest.java
This is an alternative implementation to #1768 which moves the `batchParamValues = null` to a new top-level try/finally block.
Closes #1767
=> Ensure that batchParamValues is cleared in all cases when executing a batch

CHANGELOG.md, README.md, build.gradle, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
=> Fixes for 11.2.1 hotfix

pom.xml
Latest 1.13.2 contains a bug which breaks federated authentication (see AzureAD/microsoft-authentication-library-for-java#560)
=> Revert MSAL version back to 1.13.0

src/main/java/com/microsoft/sqlserver/jdbc/SecureStringUtil.java
Fixes https://github.com/microsoft/mssql-jdbc/issues/1939
=> Added locks to encrypt/decrypt in truststore password obfuscation

CHANGELOG.md, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamDone.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/BasicConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/PropertyTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ReflectiveTests.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResiliencyUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResultSetsWithResiliencyTest.java
backport of #1857 #1943 and #1989
=> Fixed issue not checking for DONE token errors properly so exceptions are ignored (backport of 1857, 1943, 1989 to 10.2.2)

CHANGELOG.md, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
=> Fixed issue where the driver may assert when canceling a statement (backport of 1872 to 10.2.2)

CHANGELOG.md, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerJdbc43.java
=> Fix for setting KeepAlive extended options (backport of 1953 to 10.2.2)

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
Also updated `SQLJdbcVersion' file in this PR to 10.2.2.
=> Backport of #1897 - batch query cancellation fix

pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/BasicConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResultSetsWithResiliencyTest.java
=> 11.2.2 backport of 1989 and 1982 - Fixed Idle Connection recovery so that unprocessedResponseCount isn't over decremented and clear cache on recovery

pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementCancellationTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
=> 11.2.2 backport 1898 Fixed callable statement index out of bounds error; Fixed parameter not defined error

build.gradle, src/main/java/com/microsoft/sqlserver/jdbc/SecureStringUtil.java
=> 11.2.2 backport 1948 1968 Added locks to encrypt/decrypt in truststore password obfuscation and fixed race condition

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamDone.java
=> 11.2.2 backport 1943 Check for error in DONE token when fetching result sets

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
Fix for #1961. The incorrect update count can happen in both true/false cases for `enablePrepareOnFirstPreparedStatementCall` and for both prepexec/prepare.
=> Fixed incorrect updateCount

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java
=> Fixed null sql state and 0 error code for sql exceptions

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
=> Fixed incorrect updateCount (#2013)

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerJdbc42.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerJdbc43.java
=> Check for jdk.net.ExtendedSocketOptions and ignore errors

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerEnclaveProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerMSAL4JUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ConnectionSuspensionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ErrorMessageTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthCommon.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/PooledConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/BasicConnectionTest.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
- updated fedauth tests to get new access token once per test suite instead of every test
- added checks and retry for throttling
- shortened access token expiry for tests that tests token expiry
- some cleanup
=> Updated fedauth tests to run on diff test server

pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/osgi/Activator.java, src/test/java/com/microsoft/sqlserver/jdbc/osgi/DataFactoryTest.java
In the latest release of the JDBC specification there was a requirement added that datasources should promote what methods they implement. mssql-jdbc implements all methods and could therefore promote all.
This also migrates from the org.osgi.enterprise artifact to the more specific org.osgi.service.jdbc one and adds the official TCK test as part of the JUnit-Suite.
FYI @stbischof
=> Upgrade to the latest OSGi JDBC specification

build.gradle
=> Changed dependency from 'osgi.compendium' to 'osgi.service.jdbc' for build.gradle

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java
Change `supportsLikeEscapeClause() to return false if server is Azure DW, as ESCAPE clause is not supported there (https://learn.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver16).
=> Change supportsLikeEscapeClause to check for AzureDW

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
AccessToken was missing an s in the error message
=> Fix typo in error message

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java
https://github.com/microsoft/mssql-jdbc/issues/2124
=> Removed useless check

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
=> Added case for XAER_RMFAIL

mssql-jdbc.properties, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/ServerPortPlaceHolder.java
To match behavior of other drivers, serverName has been modified in LOGIN packet to include instanceName.
=> Changed serverName sent in LOGIN packet to include instanceName

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
Parameter names eg. P1, P2, ... PN will have spaces applied automatically between them.
When the driver parses `select * from table where a=?and b=?` it will become `select * from table where a= ? and b= ? `.
=> Added automatic spacing between parameter names for prepared statements

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
Backport of https://github.com/microsoft/mssql-jdbc/pull/2192.
=> Backport #2192: Added automatic spacing between parameter names for prepared SQL

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
Backport https://github.com/microsoft/mssql-jdbc/pull/2193.
=> Backport #2193: Update getUserName in impersonated security context in Azure SQL database

src/main/java/com/microsoft/sqlserver/jdbc/Util.java
Backport https://github.com/microsoft/mssql-jdbc/pull/2150.
=> Backport #2150: Change how IBM JDK is determined to fix tests and future-proof

src/main/java/com/microsoft/sqlserver/jdbc/DataTypes.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DataTypesTest.java
Fix for https://github.com/microsoft/mssql-jdbc/issues/2167.
Driver by default returns SQL-99 state codes. If `xopenStates` is set to true, driver will return X\Open state codes. SQLState code 22005 is the same in both value and meaning for SQL-99 and X\Open standards.
SQL-99 source: https://github.com/crate/sql-99/blob/main/docs/chapters/47.rst
X\Open source: [xopen_sql_states.pdf](https://github.com/microsoft/mssql-jdbc/files/12264968/xopen_sql_states.pdf)
=> Added SQLState 22005 to driver conversion exceptions

src/main/java/com/microsoft/sqlserver/jdbc/Util.java
The current `isIBM` check causes issues with OSGi environments. Instead, we're reverting to the previous check with `vendor` name, and adding an additional check with `vm` name to remove false positives, e.g. Semaru builds.
original issue #2139
=> Reverted the IBM check to vendor check AND added an additional vm name check to remove false positives

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
`schemaPattern` was the only pattern in `SQLServerDatabaseMetadata` that was not being escaped, it should be.
=> Escape schemaPattern for getSchemas

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/parametermetadata/ParameterMetaDataTest.java
fixes index issue reported in #1490
=> Fix issue with ParameterMetadata not checking for invalid index 0

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java
Prior to this PR, the column metadata query call was made every single time despite data being cached. We now only make the call if no data is cached.
Fixes https://github.com/microsoft/mssql-jdbc/issues/2224.
=> Fixed bulkcopy metadata query to make use of cached data if available

src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ResultSetsWithResiliencyTest.java
=> Randomize test table name so multiple tests can be run in parallel

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
Hello,
I'm facing a problem with the bulk API for batch insert with computed columns.
I'm using an SQL table with computed columns like
```
create table myTable (
id nvarchar(100) not null, 
json nvarchar(max) not null,
vcol1 as json_value([json], '$.vcol1')
)
```
My insert query uses for bulk:
`insert into myTable (id, json) values (?, ?)`
The current behavior of the driver is to reject the query with:
`java.sql.BatchUpdateException: The column "vcol1" cannot be modified because it is either a computed column or is the result of a UNION operator.`
After investigating and testing this fix on my project, **there is no specific reason to reject the batch insert**. The current Bulk code simply reads and compares all the columns found in the table.
I updated the current code to ignore …
=> Fix to ignore computed columns during BulkCopy

build.gradle, pom.xml, src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/KerbAuthentication.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionCertificateStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/KerberosTest.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/testframework/Constants.java
Proposal Pull Request for Issue #2172 
useDefaultGSSCredential: Boolean - by setting this property to true, mssql-jdbc will create the GSSCredential on behalf of user using Native GSS-API for kerberos authentication without attempting to perform JAAS login.
This will allow seamless integration with framework that only supports String value connection Properties such as Apache Spark
This property currently take effect only in a window. I currently don't have access to a Kerberzied Linux environment to test this. However, I supposed we could make this work on all platforms.
=> add useDefaultGSSCredential property

src/main/java/com/microsoft/sqlserver/jdbc/IdleConnectionResiliency.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Added new logger that logs details related to connection open retries and ICR reconnects only.
=> Added new named logger for connection open retries and idle connection resiliency reconnects

src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/StatementTest.java
The property is inappropriately named. It calculates precision, not scale. This is name change for the property.
=> Change name of BigDecimal computation property to `calcBigDecimalPrecision`

src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java
Please help to review this pull request for https://github.com/microsoft/mssql-jdbc/issues/2245.
CC @tkyc
=> The getters and setters for useBulkCopyForBatchInsert is not available for SQLServerConnectionPoolProxy #2245

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java
socketTimeout should be the lower of socketTimeout property value or loginTimeout
=> Ensure socketTimeout is < loginTimeout before connected

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
These changes make it so that when `useFlexibleCallableStatements=false`, setting/registering of parameters is stricter eg. either use all index or use named parameters (no mixing of index/named parameters). The reason for this is because the exceptions/cases to using index vs. named parameters are too nuanced.
=> Execute cstmt directly - Additional testing and changes

src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
=> Fix test in 2290

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java
if the caught exception does not have a cause then pass the caught exception as the cause to the SQLTimeoutException instead of the null "e.getCause()". (#2299)
=> #2299: added missing null check of e.getCause().

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
Prior to 12.6.0, all cstmts calls were wrapped int T-SQL sp_executesql, sp_prepexec etc.. calls before being sent off to the server. Doing so means the raw/unprocessed user's sql was passed into these T-SQL calls as parameter values and so the driver was able to execute "EXEC" calls against the server eg. `EXEC sp_columns_100 ?,?,?,?....`.
For example:
```
exec sp_executesql N'EXEC sp_getapplock @Resource=@P0, @LockTimeout='3600000', @LockMode='Exclusive', @LockOwner='Session',N'@P0 nvarchar(4000)',N'testParamValue'
```
This PR enables this prior behaviour again. 
https://github.com/microsoft/mssql-jdbc/issues/2323
=> Re-added support for stored procedure 'exec' escape syntax in CallableStatements

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
Port of https://github.com/microsoft/mssql-jdbc/pull/2325
=> Re-added support for stored procedure 'exec' escape syntax in CallableStatement port

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
This was incorrectly added in #1969 to address SonarQube warnings. These methods do not need to be synchronized
=> Remove synchronized from Socket overrides

src/main/java/microsoft/sql/DateTimeOffset.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DataTypesTest.java
Operates similarly to existing constructor however avoids additional expense of creating Timestamp instances and increased timezone related error potential, by directly converting java.time.OffsetDateTime instances.
Reverse of existing `DateTimeOffset.getOffsetDateTime()` method.
Rounds precision to closest 100ns matching existing semantics of `Timestamp` based constructor. Values where nanos are within 50ns of the next second are rounded upwards to the next second; as per current semantics.
Supercedes #2339
=> Allow constructing a `microsoft.sql.DateTimeOffset` instance from a `java.time.OffsetDateTime` value

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java, src/main/java/com/microsoft/sqlserver/jdbc/Util.java
https://github.com/microsoft/mssql-jdbc/issues/2346
=> Default to RMFAIL instead of RMERR

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
https://github.com/microsoft/mssql-jdbc/issues/2344
=> Fix calling procedures with output parameters by their four-part syntax

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/GuidTest.java
This PR intends to provide support for sending UUID parameters as `TDSType.GUID (0x24)` on the wire and (hopefully) implements feature request #1582. 
It currently requires the Java parameter be given to the driver as `String` with `JDBCType.GUID`, i.e. :
```
st.setObject(index, myUUID.toString(), microsoft.sql.Types.GUID);
```
=> Add support for TDSType.GUID (#1582)

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/TimeoutTest.java
https://github.com/microsoft/mssql-jdbc/issues/2354
=> socketTimeout should reset to original value after a successful connection open

src/main/java/com/microsoft/sqlserver/jdbc/ActivityCorrelator.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
address issue reported in #2136 where ActivityCorrelator ThreadLocal never being removed from the thread.
=> Fix ClassLoader leak of ActivityCorrelator ThreadLocal

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/GuidTest.java
This is a fix for the merged and reverted PR #2324.
The original PR intends to provide support for sending UUID parameters as `TDSType.GUID (0x24)` on the wire and (hopefully) implements feature request #1582. 
It currently requires the Java parameter be given to the driver as `String` with `JDBCType.GUID`, i.e. :
```
st.setObject(index, myUUID.toString(), microsoft.sql.Types.GUID);
```
=> Add support for TDSType.GUID (fix) (#1582)

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
=> Check if TDSCommand counter is null before incrementing.

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
Removed warning spam and excluded test from DW.
=> Warning log spam correction and test exclusion

CHANGELOG.md, src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyMoneyTest.java, src/test/java/com/microsoft/sqlserver/testframework/Constants.java
=> Check that money/small money are within correct range for bulkcopy

src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java
Resolve #2359 
When I am go through the test class [`RequestBoundaryMethodsTest`](https://github.com/microsoft/mssql-jdbc/blob/main/src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java), I noticed that many of the test cases in this test class is using the if condition to determine if a test should proceed based on certain preconditions. 
Here is an example from [`testWarnings`](https://github.com/microsoft/mssql-jdbc/blob/9a8849b60e74d1d01508fa61f944d9e635cab700/src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java#L171-L192):
```java
@Test
public void testWarnings() throws SQLException {
try (Connection con = getConnection()) {
if (TestUtils.isJDBC43OrGreater(con)) { \\ If Condition is false, then the whole test will …
```
=> Bring JUnit Jupiter Assumptions to `RequestBoundaryMethodsTest` to Avoid Test Case Quiet Quit

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java
Remove the unused `bulkScale` parameter in `writeSQLVariant`. Also some spelling and other small changes to this method since we have the chance to make changes. 
Original issue was created to address missing cleanup from #747.
=> Cleanup `writeSQLVariant` (removed unused parameter, remove duplicate code, spelling fixes)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSortOrder.java
Issue #2404 
Make this enum to be public, so that people can create "SQLServerMetaData" like below:
new SQLServerMetaData("row_id", java.sql.Types.INTEGER, 0, 0, true, false, SQLServerSortOrder.Unspecified, -1)
=> Make enum SQLServerSortOrder become public

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/SQLServerErrorTest.java
Added credential caching for ManagedIdentityCredential and DefaultAzureCredential.
=> Credential caching

src/main/java/com/microsoft/sqlserver/jdbc/ReconnectListener.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/BasicConnectionTest.java
Backport the user-submitted fix for clearing prepared statement handle before reconnect (#2364).
=> [Backport] Clear prepared statement handle before reconnect (2364)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java, src/main/java/com/microsoft/sqlserver/jdbc/StreamRetValue.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
RPC calls were falling back to old logic of being wrapped in sp_executesql calls to execute. With the PR, moving forward, RPC calls are also directly executed.
=> Execute stored procedures directly for RPC calls

src/main/java/com/microsoft/sqlserver/jdbc/DDC.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyAllTypesTest.java, src/test/java/com/microsoft/sqlserver/testframework/Constants.java
Backport money/smallmoney fixes for BulkCopy (#2379) as well as subsequent clean-up (#2383).
=> [Backport]  Check that money/small money are within correct range for bulkcopy (2379) & Changes to MONEY/SMALLMONEY PR (2383)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java
Backport https://github.com/microsoft/mssql-jdbc/pull/2415
=> [Backport] Added caching for Managed Identity Credential (2415)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/PoolingTest.java
Backport a fix to make sure the prepared statement cache is cleared when resetting statement pool connection (#2361).
=> [Backport] Clear prepared statement cache when resetting statement pool connection (2361)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java, src/main/java/com/microsoft/sqlserver/jdbc/SqlAuthenticationToken.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java
=> [Backport] Fix SqlAuthenticationToken constructor accepting unix epoch (2425)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java, src/main/java/com/microsoft/sqlserver/jdbc/SqlAuthenticationToken.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java
=> Fix SqlAuthenticationToken constructor accepting unix epoch

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/AESetup.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/PoolingTest.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/TimeoutTest.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthWithAE.java, src/test/java/com/microsoft/sqlserver/jdbc/fips/FipsTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resiliency/ReflectiveTests.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/SQLServerErrorTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java, src/test/java/com/microsoft/sqlserver/testframework/Constants.java
Changes required to run tests in the new yaml pipelines.
=> Managed Identity pipeline changes and test updates

CHANGELOG.md, src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/connection/TimeoutTest.java
Backport https://github.com/microsoft/mssql-jdbc/pull/2355
=> [Backport] SocketTimeout should be unbounded by loginTimeout after a successful connection open (2355)

pom.xml
Bumped MSAL to 1.15.0 and bumped azure-identity to 1.12.1.
=> MSAL and Azure Identity version bump

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java
Continuation of https://github.com/microsoft/mssql-jdbc/pull/2415.
Fixes https://github.com/microsoft/mssql-jdbc/issues/2439.
=> TokenCredential class shouldn't be required

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
If bulkcopy is used for batch insert, and if multiple `executeBatch()` calls are made against the same prepared statement, then multiple SQLServerBulkCopy objects are instantiated which will cause repeated calls to `select * sys.columns...`. This PR caches the SQLServerBulkCopy object.
=> Caching SQLServerBulkCopy object for batch insert

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
Fixes https://github.com/microsoft/mssql-jdbc/issues/2436.
=> Fixed timestamp string conversion error for cstmt

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
https://github.com/microsoft/mssql-jdbc/issues/2446
=> Fixed CallableStatement default value regression

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
Backport https://github.com/microsoft/mssql-jdbc/pull/2452
=> [Backport] Fixed CallableStatement default value regression (2452)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java
Backport https://github.com/microsoft/mssql-jdbc/pull/2441
=> [Backport] TokenCredential class shouldn't be required (2441)

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
Backport https://github.com/microsoft/mssql-jdbc/pull/2449
=> [Backport] Fixed timestamp string conversion error for cstmt (2449)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
Fixes https://github.com/microsoft/mssql-jdbc/issues/2463
=> Fixed parentheses parsing for stored procedures and functions names

CHANGELOG.md, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
Fixes https://github.com/microsoft/mssql-jdbc/issues/2477
=> Fixed regression with specifying arg names in call syntax

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
Discovered that when attempting to reuse the same pstmt object, the driver would error out with `R_multipleQueriesNotAllowed` and consume that error.
=> Prepared statement objects should be reusable

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
Backport of https://github.com/microsoft/mssql-jdbc/pull/2484.
=> [Backport] Added a missing unlock in `getDestinationMetadata()` (#2484)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
Backport of https://github.com/microsoft/mssql-jdbc/pull/2482.
=> [Backport] Prepared statement objects should be reusable (#2482)

src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
Fixes https://github.com/microsoft/mssql-jdbc/issues/2490
=> Fixed timestamp zone format

pom.xml
This PR is for being compliant with the company's security policies. Msft requires OSS project to pull from a public Azure Artifacts Feed for dependencies.
For open source contributors, you may encounter a 401 error when attempting to download dependencies. In which case, you can wait for a maintainer to update the public Azure Artifact Feed, or you can point the project's pom.xml to maven central instead to get around it.
For maintainers, any time a dependency version is updated, we also need to update the Azure Artifact Feed. Otherwise, public users won't be able to pull the dependency and our internal pipelines would fail.
Maintainers should refer to the internal doc on how to update the public Azure Artifacts Feed.
=> Compliant CFS configuration

src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ErrorMessageTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthCommon.java
Internal pipelines are failing because the error message returned from failed AAD password auth has changed. Updated tests.
=> Updated fedauth error tests

src/test/java/com/microsoft/sqlserver/jdbc/configurableretry/ConfigurableRetryLogicTest.java
Remove testing that the execution time is below a maximum for CRL. Minimum testing is required, as this tells us if a retry actually happened, but maximum can be affected by factors outside the feature and test and can not be reliably tested.
=> Remove maximum time testing from CRL

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java
Description:
Based on issue analysis 
"Could be looping infinitely because bIsClosed could be true. bIsClosed could have been set to true earlier somewhere."
we are improving the infinite loop to close all statements present in openStatements , remove them from it explicitly and terminate.
Also, it looks like this could be happening as connections/statements are being used across threads based on the issue description.
bIsClosed and openStatements are not volatile, and as a result a thread creating statements while under a request ( started using beginRequest) may add them in openStatements list, with some other thread closing them but not removing from openStatements just due to that thread having read a stale value(null) of openStatements( and other combinations of issues of this sort). …
=> issue#2537 - Fix for SQLServerConnection infinite loop

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/PooledConnectionTest.java
The SQLServerConnection connectInternal() method throws the exception R_AccessTokenCallbackWithUserPassword. This logic may be too restrictive and has therefore been removed.
=> Remove exception and validation for user/password with AccessTokenCallback

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerDriverTest.java
Use case: Update the application name to "Microsoft JDBC - {OS}, {Platform} - {architecture}"
=> Capture Client Guest OS and architecture in JDBC

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
https://github.com/microsoft/mssql-jdbc/issues/2535 - Enhance error handling in buildExecuteMetaData method to handle SQLServerException more robustly.
=> Driver cuts out the question mark from columns labels (aliases)

src/main/java/microsoft/sql/DateTimeOffset.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DataTypesTest.java
Fixed conversion of DateTimeOffset to OffsetDateTime to use Calendar class, to handle pre-Gregorian dates.
Testing:
- All tests pass
- Added a new test to test reported scenarios.
=> Fix OffsetDateTime conversion for pre-Gregorian dates

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerMSAL4JUtils.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerSecurityUtility.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java
Description:
Calls to MSAL authentication library done from the Java driver code use future.get(), potentially leading to hangs in case the library does not receive timely response from the server. All these calls done as part of getFedAuthToken need to have timeouts imposed. The timeout period is calculated based on remaining time wrt login timeout, and passed to future.get(<timeout>, <timeunit>) calls with this fix.
Tests:
- Existing unit tests pass on local build
- All ADO tests passed
- Added new tests
=> Introduced timeouts for MSAL calls.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java
Set appropriate value to requestedEncryptionLevel for encrypt=STRICT
=> Set appropriate value to requestedEncryptionLevel for encrypt=STRICT

src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ConcurrentLoginTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ConnectionEncryptionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/ErrorMessageTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthCommon.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthTest.java, src/test/java/com/microsoft/sqlserver/jdbc/fedauth/FedauthWithAE.java
this re-enables all fedauth tests other than ones which specifically require secrets which will still use the requireSecret tag
=> Update FedAuth tests to use ManagedIdentity

pom.xml
The change done in PR https://github.com/microsoft/mssql-jdbc/pull/2609/ got reverted in PR https://github.com/microsoft/mssql-jdbc/pull/2614.
This PR is to restore it back to address the issue reported in issue #2635
=> Make ibm security module optional

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
Github Issue: https://github.com/microsoft/mssql-jdbc/issues/2639 
Fixed incorrect filtering behavior in DatabaseMetaData.getSchemas when a specific catalog name is provided. Previously, the driver returned system/predefined schemas with a null catalog even when a catalog was specified, violating the JDBC specification. This update ensures that only schemas belonging to the specified catalog are returned, and system schemas without a catalog are properly excluded from the result set.
=> Fixed getSchemas catalog filtering logic and added test case to validate built-in schema handling (#2639)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Warning message to indicaite deprecation of ActiveDirectoryPassword authentication method.
=> Added warning for ActiveDirectoryPassword authentication method

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/SavepointTest.java
Fixed exception type to SQLfeatureNotSupported as per the the java.sql.Connection API doc: https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#releaseSavepoint-java.sql.Savepoint-
Testing:
- Build and unit tests pass
- Added new unit test for testing this exception
-
=> Fixed exception type to SQLFeatureNotSupported

src/main/java/com/microsoft/sqlserver/jdbc/ConfigurableRetryLogic.java
Related Github issue -> https://github.com/microsoft/mssql-jdbc/issues/2646
=> Update readFromFile() in ConfigurableRetryLogic to handle filePath related issues

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/SQLServerDataTableTest.java
When OffsetDateTime contains zero seconds, calling toString() produces the following format: 2025-04-26T19:42+02:00 (without seconds) which is rejected by the server with the message "Conversion failed when converting date and/or time from character string." (SQL Error: 241, SQLState: S0001)
=> correct processing of OffsetDateTime in SQLServerDataTable 

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java, src/test/java/com/microsoft/sqlserver/jdbc/tvp/SQLServerDataTableTest.java
Noticed that it was using == on strings in the equals function for SQLServerDataTable. (I didn't experience a bug as a result of it) Is it intended to check the memory location?
=> Improvement to equals in SQLServerDataTable

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java, src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
Replaced the use of the sp_statistics stored procedure with a custom query to retrieve index information as the sp_statistics procedure did not return Columnstore indexes, so a query using sys.indexes was implemented as a workaround.
This new query ensures that all index types (Clustered, NonClustered, Columnstore) are included in the result set.
Github Issue: https://github.com/microsoft/mssql-jdbc/issues/2546
=> Updated getIndexInfo() to include Columnstore indexes by using custom query.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
Issue: https://github.com/microsoft/mssql-jdbc/issues/2654
Details (copied from above issue)
Fabric has introduced a feature that can cause clients to be redirected more than once. The JDBC driver currently limits connections to one redirection.
Describe the preferred solution
M.D.SqlClient has increased their limit to 10 redirections. Other drivers should follow suit and not error until redirection attempts exceed 10.
=> Increased the max noOfRedirections and updated the message.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/AESetup.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/RegressionAlwaysEncryptedTest.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatementMockTest.java, src/test/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatementTest.java
**Description:**
- The incident involved unexpected behavior when inserting strings using Always Encrypted with Secure Enclaves in Azure SQL DB.
- Unexpected insert results when using Always Encrypted.
- Subsequent inserts into encrypted columns fail after initial successful inserts.
- Issue in details at code level:
The buildPreparedStrings method compares the last prepared statement with the current one to be executed. If both statements are identical, it signals that calling sp_prepexec is unnecessary. Otherwise, sp_prepexec will be invoked later in the driver's execution flow. However, multiple calls to buildPreparedStrings overwrite the preparedTypeDefinitions variable, which stores the current prepared statement. As a result, repeated invocations can lead to the loss of the original …
=> Handled sp_prepexec call for Column encryption enabled

pom.xml
Backported PR: https://github.com/microsoft/mssql-jdbc/pull/2636
* Make ibm security module optional
* Formatted the change
=> Backport: Make ibm security module optional (#2636)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
Backported PR: https://github.com/microsoft/mssql-jdbc/pull/2659
Fabric has introduced a feature that can cause clients to be redirected more than once. The JDBC driver currently limits connections to one redirection.
Describe the preferred solution
M.D.SqlClient has increased their limit to 10 redirections. Other drivers should follow suit and not error until redirection attempts exceed 10.
=> Backport: Increased the max noOfRedirections and updated the message. (#2659)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/AESetup.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/RegressionAlwaysEncryptedTest.java
Backported PR: https://github.com/microsoft/mssql-jdbc/pull/2674
* Fixed New Type Param Definitions logic in doExecutePreparedStatement
* Added clearParameters() method in very string length insert in encrypted column while AE enabled4
* Fixed: hasNewTypeDefinitions flag is set only once in doExecutePreparedStatement(), based on the result of the first call to buildPreparedString()
=> Backport: Fixed New Type Param Definitions logic in doExecutePreparedStatement

src/main/java/com/microsoft/sqlserver/jdbc/KeyStoreProviderCommon.java, src/main/java/com/microsoft/sqlserver/jdbc/NTLMAuthentication.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCertificateUtils.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionJavaKeyStoreProvider.java, src/main/java/com/microsoft/sqlserver/jdbc/SecureStringUtil.java
Description
CodeQL static analysis raised warnings for certain cryptographic algorithms and usages in the JDBC driver codebase. These warnings were triggered in files supporting NTLM authentication, Always Encrypted, legacy private key handling, and secure in-memory string encryption. However, these usages are intentional and required for compatibility with SQL Server features, industry standards, and appropriate security contexts.
Resolution details:
This PR adds CodeQL suppression comments to the affected lines of code. These suppressions are justified and documented to ensure clarity and maintain compliance with external standards or backward compatibility. No functional code changes were made. The updates are as follows:
1. NTLMAuthentication.java (lines 605, 825)
Suppression added …
=> Addressed and suppressed CodeQL warnings with explanatory comments in the JDBC codebase.

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkBatchInsertRecord.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
This PR addresses GitHub reported issue : [Bulk copy for batch insert destroys data without error #2669](https://github.com/microsoft/mssql-jdbc/issues/2669)
When inserting string data using batch insert for bulk copy with below combinations:
```
- useBulkCopyForBatchInsert=true
- sendStringParametersAsUnicode=false
```
The data is inserted in byte array format. 
**Expected behavior**
Select StateCode from states -> "OH"
**Actual behavior**
Select StateCode from states; -> "[B@4b01d9e4"
The issue occurs because:
- When sendStringParametersAsUnicode=false, the setString() method stores parameter values as byte arrays in the DTV (Data Type Value) objects.
- During bulk copy batch insert, the SQLServerBulkBatchInsertRecord.convertValue() method retrieves these raw byte arrays from the …
=> Update batch insert for bulk copy operation to handle string correctly when sendStringParametersAsUnicode is set to false

.github/PULL_REQUEST_TEMPLATE/pr-template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, coding-best-practices.md, review-process.md
Description:
Introduced contributing guidelines, coding best practices, and review process for mssq-jdbc.
=> Coding best practices and review process for mssql-jdbc

src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
The JDBC driver was not properly consulting the JVM system property `javax.net.ssl.trustStoreType` when the `trustStoreType` connection property was not explicitly set. This affected all SSL connection scenarios where users expected `-Djavax.net.ssl.trustStoreType=Windows-ROOT` (or other values) to be honored.
The trust manager selection logic in `IOBuffer.enableSSL()` was missing the standard fallback hierarchy for `trustStoreType` resolution when entering the KeyStore loading path.
Added comprehensive JVM system property consultation logic that follows the standard Java property resolution hierarchy:
1. Check connection property `trustStoreType`
2. If empty, check JVM system property `javax.net.ssl.trustStoreType`
3. If still empty, use default value "JKS"
- **IOBuffer.java**: Added …
=> Fix trustStoreType JVM property consultation in SSL connections (#2691)

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkBatchInsertRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
Reverts microsoft/mssql-jdbc#2727
This issue will be addressed in [Addressed performance issue on Bulk Copy API with batch insert #2735](https://github.com/microsoft/mssql-jdbc/pull/2735)
=> Revert "Properly Insert Accented Characters When Using Bulk Copy and Non-Unicode Strings"

src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkBatchInsertRecord.java, src/main/java/com/microsoft/sqlserver/jdbc/dtv.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java
A GitHub issue was raised highlighting a performance degradation in the Bulk Copy API when using batch inserts
[Pre-release 13.1 is slower #2732](https://github.com/microsoft/mssql-jdbc/issues/2732)
The original issue reported was [Bulk copy for batch insert destroys data without error #2669](https://github.com/microsoft/mssql-jdbc/issues/2669)
This occurred when inserting string data using the following settings:
```
- useBulkCopyForBatchInsert=true
- sendStringParametersAsUnicode=false
```
Under these conditions, data was inserted in byte array format rather than as readable strings.
Expected behavior
Select StateCode from states -> "OH"
Actual behavior
Select StateCode from states; -> "[B@4b01d9e4"
On top of this a new issue was reported [Accented characters saved incorrectly in …
=> Addressed performance issue on Bulk Copy API with batch insert

src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
- getFunctions() and getProcedures() internally call sp_stored_procedures, which always returns the object type as 2 and the object name as a numbered procedure.
- Similarly, getFunctionColumns() and getProcedureColumns() rely on sp_sproc_columns, which also returns numbered procedures.
This behavior is consistent with how the server returns the values.
Added test scenarios for the above APIs to validate and cover the expected results
=> Added scenarios to validate existing behaviour of getFunctions(), getProcedures(), getFunctionColumns() and getProcedureColumns() APIs

src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/BulkCopySendTemporalDataTypesAsStringAETest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/EnclaveTest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/MSITest.java, src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/RegressionAlwaysEncryptedTest.java, src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyISQLServerBulkRecordTest.java, src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/DateAndTimeTypeTest.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/JSONFunctionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/VectorTest.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java, src/test/java/com/microsoft/sqlserver/jdbc/resultset/ResultSetTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java, src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/CallableMixedTest.java, src/test/java/com/microsoft/sqlserver/testframework/AbstractSQLGenerator.java
During review of #2705, I noticed a lot of old test objects in the logs. This PR updates a few tests that weren't cleaning up after themselves appropriately.
=> Add missing test object cleanup calls

src/main/java/com/microsoft/sqlserver/jdbc/VectorUtils.java
Backported PR: https://github.com/microsoft/mssql-jdbc/pull/2750
After adding https://github.com/microsoft/mssql-jdbc/pull/2634, we observed failures on JDK 8 due to a NoSuchMethodError when invoking ByteBuffer.position(int).
In JDK 8, Buffer.position(int) returns Buffer.
In JDK 9+, ByteBuffer overrides this method to return ByteBuffer.
Directly calling ByteBuffer.position(int) caused incompatibility and resulted in NoSuchMethodError on JDK 8.
Cast the ByteBuffer instance to Buffer before calling position().
This ensures consistent behavior across JDK 8 and newer versions.
Verified all vector-related tests locally.
Confirmed successful execution on JDK 8 as well as later JDK versions.
=> Backport : JDK 8 compatibility fix for vector datatype handling

src/main/java/com/microsoft/sqlserver/jdbc/VectorUtils.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyCSVTest.java, src/test/java/com/microsoft/sqlserver/jdbc/bulkCopy/BulkCopyISQLServerBulkRecordTest.java, src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java, src/test/java/com/microsoft/sqlserver/jdbc/datatypes/VectorTest.java, src/test/java/com/microsoft/sqlserver/jdbc/preparedStatement/BatchExecutionWithBulkCopyTest.java, src/test/java/com/microsoft/sqlserver/testframework/AzureDB.java, src/test/java/com/microsoft/sqlserver/testframework/VectorTag.java
Backported PR: https://github.com/microsoft/mssql-jdbc/pull/2749
This PR introduces support for running vector tests exclusively on AzureDB, where vector functionality is available. Key changes include:
- Vector Support in AzureDB: Tests for vector features are enabled only when running against AzureDB, ensuring compatibility and reducing noise on unsupported platforms.
- Custom JUnit Annotation: Added a custom JUnit annotation to selectively run relevant tests in AzureDB environments.
These changes help streamline the test suite and maintain focus on supported scenarios.
=> Backport : Enable vector test to run only in AzureDB

pom.xml
This PR is for being compliant with the company's security policies. Msft requires OSS project to pull from a public Azure Artifacts Feed for dependencies.
For open source contributors, you may encounter a 401 error when attempting to download dependencies. In which case, you can wait for a maintainer to update the public Azure Artifact Feed, or you can point the project's pom.xml to maven central instead to get around it.
For maintainers, any time a dependency version is updated, we also need to update the Azure Artifact Feed. Otherwise, public users won't be able to pull the dependency and our internal pipelines would fail.
Maintainers should refer to the internal doc on how to update the public Azure Artifacts Feed.
=> Update pom.xml to use Azure Artifacts feed for mssql-jdbc 12.8

pom.xml
This PR is for being compliant with the company's security policies. Msft requires OSS project to pull from a public Azure Artifacts Feed for dependencies.
For open source contributors, you may encounter a 401 error when attempting to download dependencies. In which case, you can wait for a maintainer to update the public Azure Artifact Feed, or you can point the project's pom.xml to maven central instead to get around it.
For maintainers, any time a dependency version is updated, we also need to update the Azure Artifact Feed. Otherwise, public users won't be able to pull the dependency and our internal pipelines would fail.
Maintainers should refer to the internal doc on how to update the public Azure Artifacts Feed.
=> Update pom.xml to use Azure Artifacts feed for mssql-jdbc 12.4

pom.xml
This PR is for being compliant with the company's security policies. Msft requires OSS project to pull from a public Azure Artifacts Feed for dependencies.
For open source contributors, you may encounter a 401 error when attempting to download dependencies. In which case, you can wait for a maintainer to update the public Azure Artifact Feed, or you can point the project's pom.xml to maven central instead to get around it.
For maintainers, any time a dependency version is updated, we also need to update the Azure Artifact Feed. Otherwise, public users won't be able to pull the dependency and our internal pipelines would fail.
Maintainers should refer to the internal doc on how to update the public Azure Artifacts Feed.
=> Update pom.xml to use Azure Artifacts feed for mssql-jdbc 12.2
